### PR TITLE
jbide-23900: refactoring of openshift server adapter

### PR DESCRIPTION
**Pull request by bdshadow**
The PR is ready for trying!
@adietish @jeffmaury @robstryker please, take a look at the code and try it.
Still going to add some tests + maybe some small fixes, but i've already tried it with some basic scenarios and it worked for me. 
I'm looking forward to your comments!

### CODE REVIEW

**Comment by jeffmaury** [comment]
I tried on Win10 with EAP64 in the following configurations:

- standard (service + BC/DC)
- no service (BC/DC only)
- RC only (no BC/DC)
I had rsync and port forward errors but they seem to be Windows related
Will try on my RHEL VM

**Comment by bdshadow** [comment]
I've created a wiki here https://github.com/jbosstools/jbosstools-openshift/wiki/Openshift-server-adapter-profile-and-its-subsystems, to understand my refactoring and to make it easier to create openshfit server adapter extension in the future.

**Comment by jeffmaury** [comment]
Tried on RHEL VM but got this error when creating a server adapter for NodeJS:!ENTRY org.eclipse.ui 4 0 ```
!ENTRY org.jboss.tools.openshift.core 4 0 2017-04-11 14:00:13.477
!MESSAGE Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.getSubsystemMappingForCreation(SubsystemModel.java:409)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:460)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:362)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:342)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ServerProfileModel.getController(ServerProfileModel.java:190)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ProfileServerBehavior.getController(ProfileServerBehavior.java:59)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ProfileServerBehavior.getModuleStateController(ProfileServerBehavior.java:32)
	at org.jboss.tools.openshift.core.server.OpenShiftServerBehaviour.launchPostStartupJobs(OpenShiftServerBehaviour.java:58)
	at org.jboss.tools.openshift.core.server.OpenShiftServerBehaviour.setServerStarted(OpenShiftServerBehaviour.java:37)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.setServerState(OpenShiftLaunchController.java:219)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.toggleDebugging(OpenShiftLaunchController.java:200)
	at org.jboss.tools.openshift.js.server.behaviour.OpenshiftNodejsLaunchController.launch(OpenshiftNodejsLaunchController.java:44)
	at org.jboss.ide.eclipse.as.wtp.core.server.launch.ControllableServerLaunchConfiguration.launch(ControllableServerLaunchConfiguration.java:52)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:731)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3556)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3492)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:367)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
!SUBENTRY 1 org.jboss.ide.eclipse.as.wtp.core 4 0 2017-04-11 14:00:13.477
!MESSAGE Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
```

**Comment by bdshadow** [comment]
@jeffmaury fixed the issue, could you, please, test it once again

**Comment by jeffmaury** [comment]
Works better for NodeJS now but got this error when playing with EAP:

`
!ENTRY org.jboss.tools.openshift.core 2 0 2017-04-13 11:06:48.631
!MESSAGE Error while publishing server jboss-eap70-openshift (Service) at OpenShift 3 (10.1.2.2).  Could not sync all pods to folder /home/jeffmaury/runtime-JBossTools/.metadata/.plugins/org.jboss.ide.eclipse.as.core/eap@jboss-eap70-openshift/deploy
!STACK 1
org.eclipse.core.runtime.CoreException: Error while publishing server jboss-eap70-openshift (Service) at OpenShift 3 (10.1.2.2).  Could not sync all pods to folder /home/jeffmaury/runtime-JBossTools/.metadata/.plugins/org.jboss.ide.eclipse.as.core/eap@jboss-eap70-openshift/deploy
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftPublishController.publishStart(OpenShiftPublishController.java:73)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.CachedPublisherProfileBehavior.publishStart(CachedPublisherProfileBehavior.java:47)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:942)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3172)
	at org.eclipse.wst.server.core.internal.Server.publish(Server.java:1330)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController$1.run(OpenShiftLaunchController.java:238)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Contains: Syncing com.openshift.restclient.capability.resources.IRSyncable$PodPeer@5e1a8dec to com.openshift.restclient.capability.resources.IRSyncable$LocalPeer@4f0e0c05 failed: could not make way for new regular file: ROOT.war
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1518) [generator=3.0.9]
error: exit status 23

!SUBENTRY 1 org.jboss.tools.openshift.core 4 0 2017-04-13 11:06:48.631
!MESSAGE Error while publishing server jboss-eap70-openshift (Service) at OpenShift 3 (10.1.2.2).  Could not sync all pods to folder /home/jeffmaury/runtime-JBossTools/.metadata/.plugins/org.jboss.ide.eclipse.as.core/eap@jboss-eap70-openshift/deploy
!SUBENTRY 2 org.jboss.tools.openshift.core 4 0 2017-04-13 11:06:48.631
!MESSAGE Syncing com.openshift.restclient.capability.resources.IRSyncable$PodPeer@5e1a8dec to com.openshift.restclient.capability.resources.IRSyncable$LocalPeer@4f0e0c05 failed: could not make way for new regular file: ROOT.war
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1518) [generator=3.0.9]
error: exit status 23

`

And this is not reported to the user but only in the log file, I had the impression it was reported to the user before

**Comment by bdshadow** [comment]
@jeffmaury looks like i've seen it already. Does it happen only with my PR? Seems it should happen with current master branch too, because i didn't touch the logic of working with server apapter for eap itself.

**Comment by bdshadow** [comment]
@jeffmaury checked it in master. Had the same exception. So it's not a problem of the refactoring.
Going to rebase it because of conflicts

**Comment by bdshadow** [comment]
rebased it. @jeffmaury @robstryker @adietish if you don't have any remarks, i want to merge it today until the code freeze

**Pull request merged**
