### PR TITLE
JBIDE-26470 - Fix Java11+ compilation error

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jeffmaury** [comment]
testPR

**Comment by adietish** [comment]
false positive in egit tests. Re-launching tests.

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury strange that sonar is not being triggered?

**Comment by jeffmaury** [comment]
Probably because no code change !

**Pull request merged**
