### PR TITLE
[JBIDE-21318] use proper OpenShift version in server labels

### PR DESCRIPTION
**Pull request by fbricon**
Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Comment by adietish** [comment]
+1 for the quick fix for now.

**Comment by scabanovich** [comment]
May I mention here a potential NPE in Connection.equals(). Comparing for clients goes  
		if (client == null) {
			if (other.client != null)
				return false;
		} else if (!client.getBaseURL().toString().equals(other.client.getBaseURL().toString()))
			return false;
When this.client is not null, other.client is not checked for null though checks above imply that it is possible.

**Comment by adietish** [comment]
+1, goo catch, thanks!

**Comment by adietish** [comment]
PR'ed in #856

**Pull request merged**
