### PR TITLE
JBIDE-25212 JBIDE-25277 CreateResourcesTest and ImportApplicationWizardGitTest Tests Stabilization

### PR DESCRIPTION
**Pull request by jkopriva**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
Jenkins build with stable suite: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift.itests/60/

**Comment by adietish** [comment]
when running the tests I have 3 errors:
```
org.jboss.tools.openshift.ui.bot.test.integration.docker.DeployDockerImageTest no-configuration  Time elapsed: 11.364 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.jboss.tools.openshift.ui.bot.test.integration.docker.DeployDockerImageTest.createDockerConnection(DeployDockerImageTest.java:113)
	at org.jboss.tools.openshift.ui.bot.test.integration.docker.DeployDockerImageTest.setUp(DeployDockerImageTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunBeforeClasses.evaluate(RunBeforeClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:56)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:152)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)

testShowDefinedResourcesForServerTemplate no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.NewApplicationWizardHandlingTest)  Time elapsed: 7.193 sec
testFilteringServerTemplates no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.NewApplicationWizardHandlingTest)  Time elapsed: 3.165 sec
testTemplatesRelatedWidgetAccess no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.NewApplicationWizardHandlingTest)  Time elapsed: 5.27 sec
testShowDefinedResourcesForLocalTemplate no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.NewApplicationWizardHandlingTest)  Time elapsed: 3.939 sec
testSwitchProject no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.NewApplicationWizardHandlingTest)  Time elapsed: 3.429 sec
testAccessibilityOfDefinedResourcesButton no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.NewApplicationWizardHandlingTest)  Time elapsed: 8.571 sec
testModifyTemplateParameter no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.TemplateParametersTest)  Time elapsed: 3.625 sec
testTemplateParametersDefaultValues no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.TemplateParametersTest)  Time elapsed: 3.345 sec
testTemplateParameterDetails no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.TemplateParametersTest)  Time elapsed: 3.255 sec
editLabel no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 6.543 sec
testLabelValueValidation no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 24.677 sec
testCreateDuplicativeReadOnlyLabel no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 13.806 sec
testBasicLabelValidation no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 7.556 sec
deleteLabel no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 3.802 sec
manageReadOnlyLabels no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 7.268 sec
createLabel no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 3.755 sec
testLabelNameValidation no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 25.954 sec
testCreateDuplicativeLabel no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.basic.LabelsTest)  Time elapsed: 14.223 sec
org.jboss.tools.openshift.ui.bot.test.application.v3.adapter.ImportApplicationWizardTest no-configuration  Time elapsed: 60.786 sec  <<< ERROR!
org.eclipse.reddeer.jface.exception.JFaceLayerException: There are more items matching specified path so result is ambiguous. To obtain all such items, please use method getTreeItems with same parameters
	at org.eclipse.reddeer.jface.handler.TreeViewerHandler.getTreeItem(TreeViewerHandler.java:74)
	at org.eclipse.reddeer.jface.handler.TreeViewerHandler.getTreeItem(TreeViewerHandler.java:67)
	at org.jboss.tools.openshift.reddeer.view.resources.OpenShiftProject.getService(OpenShiftProject.java:54)
	at org.jboss.tools.openshift.ui.bot.test.application.v3.adapter.ImportApplicationBase.init(ImportApplicationBase.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunBeforeClasses.evaluate(RunBeforeClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:56)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:152)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)

org.jboss.tools.openshift.ui.bot.test.application.v3.adapter.ImportApplicationWizardGitTest no-configuration  Time elapsed: 113.737 sec  <<< ERROR!
org.eclipse.reddeer.jface.exception.JFaceLayerException: There are more items matching specified path so result is ambiguous. To obtain all such items, please use method getTreeItems with same parameters
	at org.eclipse.reddeer.jface.handler.TreeViewerHandler.getTreeItem(TreeViewerHandler.java:74)
	at org.eclipse.reddeer.jface.handler.TreeViewerHandler.getTreeItem(TreeViewerHandler.java:67)
	at org.jboss.tools.openshift.reddeer.view.resources.OpenShiftProject.getService(OpenShiftProject.java:54)
	at org.jboss.tools.openshift.ui.bot.test.application.v3.adapter.ImportApplicationBase.init(ImportApplicationBase.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunBeforeClasses.evaluate(RunBeforeClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:56)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:152)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)

testOpenCreateResourceWizardViaContextMenuOfProject no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.advanced.CreateResourcesTest)  Time elapsed: 10.159 sec
testCreateResourceFromURL no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.advanced.CreateResourcesTest)  Time elapsed: 18.996 sec
testOpenCreateResourceWizardViaContextMenuOfConnection no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.advanced.CreateResourcesTest)  Time elapsed: 9.841 sec
testCreateResourceFromLocalFile no-configuration(org.jboss.tools.openshift.ui.bot.test.application.v3.advanced.CreateResourcesTest)  Time elapsed: 28.863 sec

Results :

Tests in error:
  null
  There are more items matching specified path so result is ambiguous. To obtain all such items, please use method getTreeItems with same parameters
  There are more items matching specified path so result is ambiguous. To obtain all such items, please use method getTreeItems with same parameters

Tests run: 46, Failures: 0, Errors: 3, Skipped: 2
```

image

image

image

But somehow it also looks like I'm maybe running the wrong framework version ("org.eclipse.reddeer.jface.exception.JFaceLayerException: There are more items matching specified path so result is ambiguous. To obtain all such items, please use method getTreeItems with same parameters")?

**Comment by jkopriva** [comment]
@adietish can you please review? On Jenkins it runs on rhel and Win10, Fedora fails due to timeout error(probably it is not related to this change, but to slave itself - I will try to investigate and fix in another PR): https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift.itests/95/

**Comment by jkopriva** [comment]
testPR

**Pull request merged**
