### PR TITLE
JBIDE-27546: node debug breakpoints are not honored

### PR DESCRIPTION
**Pull request by jeffmaury**
- Configure root for devfile components
- Add RedDeer ITs
- Add RedDeer terminal view implementation

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
@jeffmaury Hi, thank you for integration tests :) Were you able to run tests without issues? I am still getting some errors, when running the tests...

**Comment by jeffmaury** [comment]
@jkopriva yes except the one that has @Ignore because generated project is incompatible with devfile

**Comment by jkopriva** [comment]
@jeffmaury ok, then LGTM, I will try to fix my failures running the tests after this PR is merged.

**Comment by jkopriva** [comment]
@jeffmaury can you please check formatting of some files? Thank you!

**Review by sbouchet — COMMENTED** [review]
LGTM. did a local run and have no errors. BUT I had to change a lot of BREE to JavaSE-11 to make it work.

**Pull request merged**
