### PR TITLE
[JBIDE-26411] corrected MANIFEST to use commons-compress 1.18

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
common-compress 1.8.1 should be used across the board, currently pom is using 1.18. This PR fixes it:

* in .classpath: 1.8.1 https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.client/.classpath#L4
* in MANIFEST: 1.8.1: https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF#L14
2:14 PM
* in pom: currently 1.18, should be 1.8.1: https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.client/pom.xml#L23

**Comment by bdshadow** [comment]
1.8.1 is an older version than 1.18 according to https://mvnrepository.com/artifact/org.apache.commons/commons-compress

After a discussion with @adietish he told me that he and @robstryker came to a decision that in order to make it consistent everywhere (jbosstools-openshift and openshift-rest-client) it's better to downgrade the version to 1.8.1 here in one place instead of upgrading it to 1.18 everywhere and then checking if it works correctly.

**Comment by adietish** [comment]
the thing that I oversaw is that compress was bumped to 1.18 by jeff maury back in the following commit:
```
commit 2a5a5cec9a5a612bdf35d1aa2116ffde2f9fca50
Author: Jeff MAURY <jeffmaury.github@jeffmaury.com>
Date:   Fri Oct 5 11:45:15 2018 +0200

    Switch to latest commons compress to fix security issue reported by snyk.io (#1801)

    Signed-off-by: Jeff MAURY <jmaury@redhat.com>

diff --git a/plugins/org.jboss.tools.openshift.client/pom.xml b/plugins/org.jboss.tools.openshift.client/pom.xml
index 97e500cc9..10adaf550 100644
--- a/plugins/org.jboss.tools.openshift.client/pom.xml
+++ b/plugins/org.jboss.tools.openshift.client/pom.xml
@@ -21,7 +21,7 @@
                <ok-http-ws.version>3.3.1</ok-http-ws.version>
                <ok-io.version>1.8.0</ok-io.version>
                <jboss-dmr.version>1.3.0.Final</jboss-dmr.version>
-               <commons-compress.version>1.8.1</commons-compress.version>
+               <commons-compress.version>1.18</commons-compress.version>
                <log4j.version>1.2.17</log4j.version>
                <slf4j-api.version>1.6.1</slf4j-api.version>
                <slf4j-log4j12.version>1.6.1</slf4j-log4j12.version>
```

**Comment by jeffmaury** [comment]
Yes bump to 1.18 was there to prevent a security issue so why reverting that and not switching everywhere to 1.18 ?

**Comment by adietish** [comment]
@jeffmaury @bdshadow sorry, it's all my fault. My commit to use the latest openshift-restclient-java reverted the change that rob did. I updated my commit accordingly.

**Pull request merged**
