### PR TITLE
JBIDE-25194 OpenShift IO Integration test

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
It will be included in StableSuite after https://issues.jboss.org/browse/JBIDE-25390 is resolved.

**Comment by jkopriva** [comment]
testPR

**Comment by adietish** [comment]
@jkopriva openshift ITs and also cdk/openshift ITs are both unstable. Not sure including this PR or not changes anything and prevents merging. Does it?

**Comment by jkopriva** [comment]
@adietish This test is not included in Stable suite, so it should not affect openshift.itests job on Jenkins. (I have tried it on different machines and I have experienced issues only on jenkins slaves - not sure why)

**Comment by adietish** [comment]
@jkopriva can you please rebase? Once we're back in green I'd love to merge this.

**Pull request merged**
