### PR TITLE
JBIDE-26339 - Update cdk.itests to use minishift 1.24

### PR DESCRIPTION
**Pull request by odockal**
- Add another release minishift version
   - Make CDKRuntimeDetectionTest robust

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jkopriva @odockal can we merge this?

**Comment by odockal** [comment]
@adietish I rebased the branch and pushed it, so let it build and merge if no problem occurs.

**Comment by adietish** [comment]
@odockal thx! I believe that we have to 1st version bump openshift: https://issues.jboss.org/browse/JBIDE-26417

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
[build 1898](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-openshift-Pull-Request/1898/) failed with the error that PR #1808 fixed. [1899] (https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-openshift-Pull-Request/1899/) is back to green. Dont know why the status wasn't updated in this PR

**Comment by adietish** [comment]
@odockal you need to rebase this to get a green build.

**Pull request merged**
