### PR TITLE
[JBIDE-20167] added usage tracking

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
You are counting OS wizards starts and finishes as one event.
For example if you start the wizard 5 times in total during the 24 hours. But twice cancel the wizard and three times press finish with failure you will track this event as: 
Action: "new_app"
Label: <OS version>
Value: 5
But if you start it 3 times, two times finished with success and one with failure then you will track the same event:
Action: "new_app"
Label: <OS version>
Value: 5
In the first case you will count: 5(starts) * 1(default value) + 3(finish)*0(failure) = 5
In the second: 3(starts)*1(default value) + 2(finish)*1(success) + 1(finish)*0(failure) = 5
I assume you used the same OS version in these examples.

1. If you want to track all starts of the wizards and all the finishes then you have to use two separate event types with different actions.
2. If you want to track success/failures then you have two options:

a) don't count events for every 24 hours. Send them as soon as the event happened. Like we do for New Server wizard: https://github.com/jbosstools/jbosstools-server/blob/jbosstools-4.2.0.Beta1x/as/plugins/org.jboss.ide.eclipse.as.ui/jbossui/org/jboss/ide/eclipse/as/ui/wizards/ServerProfileWizardFragment.java#L404-L405
In this case you the number of sent events will show you the number of finished wizards. And the sum of all these event's values will show you the number of successful ones.

b) Count successful events and failures as separate events. Two event types with different actions.

**Comment by alexeykazakov** [comment]
And what about tracking "redhat"/others host names?

**Comment by alexeykazakov** [comment]
What we could do:

```java
UsageEventType eventTypeV2 = new UsageEventType(OPENSHIFT_COMPONENT, UsageEventType.getVersion(OpenShiftCommonUIActivator.getDefault()), null,
	"new_app_v2", // actionName
	"host type: redhat/other", // labelDescription if it makes sense for OS2. All hosts are "redhat" in v2, correct?
	 UsageEventType.SUCCESFULL_FAILED_VALUE_DESCRIPTION);
UsageEventType eventTypeV3 = new UsageEventType(OPENSHIFT_COMPONENT, UsageEventType.getVersion(OpenShiftCommonUIActivator.getDefault()), null,
	"new_app_v3", // actionName
	"host type: redhat/other", // labelDescription
	 UsageEventType.SUCCESFULL_FAILED_VALUE_DESCRIPTION);
...
// When pressFinish happened for v2:
UsageReporter.getInstance().trackEvent(eventTypeV2.event("redhat", succesful));
// When pressFinish happened for v3:
UsageReporter.getInstance().trackEvent(eventTypeV3.event(hostType, succesful));
```

**Comment by adietish** [comment]
@fbricon dare to review?

**Comment by fbricon** [comment]
LGTM

**Pull request merged**
