### PR TITLE
[JBIDE-19626] Fix refresh resources

### PR DESCRIPTION
**Pull request by jcantrill**
@adietish This fixes the refresh and 'double' loading issues we have.  The only thing that is a little off is the refresh that collapse the whole tree.  I think the only fix to this would be to utilize adapter classes that extend from observable pojo.  Thoughts?

### CODE REVIEW

**Comment by adietish** [comment]
Code looks good afaics. But functionwise there's still a problem:
If I apply it, make sure my openshift container is not running and then unfold the connection in the explorer, I have an exception that keeps popping up in the log and in an error dialog:
repeated-error-while-loading

`!MESSAGE An internal error occurred during: "Loading OpenShift resources...".
!STACK 0
com.openshift.internal.restclient.http.HttpClientException: java.net.ConnectException: Connection refused
	at com.openshift.internal.restclient.http.UrlConnectionHttpClient.createException(UrlConnectionHttpClient.java:217)
	at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:151)
	at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:130)
	at com.openshift.internal.restclient.http.UrlConnectionHttpClient.get(UrlConnectionHttpClient.java:92)
	at com.openshift.internal.restclient.DefaultClient.getVersion(DefaultClient.java:297)
	at com.openshift.internal.restclient.DefaultClient.getOpenShiftVersions(DefaultClient.java:273)
	at com.openshift.internal.restclient.DefaultClient.getOpenShiftAPIVersion(DefaultClient.java:287)
	at com.openshift.internal.restclient.DefaultClient.getTypeMappings(DefaultClient.java:322)
	at com.openshift.internal.restclient.DefaultClient.list(DefaultClient.java:109)
	at com.openshift.internal.restclient.DefaultClient.list(DefaultClient.java:103)
	at com.openshift.internal.restclient.DefaultClient.list(DefaultClient.java:98)
	at org.jboss.tools.openshift.core.connection.Connection.get(Connection.java:257)
	at org.jboss.tools.openshift.internal.ui.explorer.OpenShiftExplorerContentProvider.getChildrenFor(OpenShiftExplorerContentProvider.java:56)
	at org.jboss.tools.openshift.internal.common.ui.explorer.BaseExplorerContentProvider$1.run(BaseExplorerContentProvider.java:124)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.net.ConnectException: Connection refused
	at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.openshift.internal.restclient.http.UrlConnectionHttpClient.createException(UrlConnectionHttpClient.java:200)
	... 14 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:147)
	... 13 more`

**Comment by jcantrill** [comment]
@adietish I believe latest commit fixes the issue.  Fixes some refresh problems with the caveat that we will only refresh connections and groups.  Follow on work to be able to refresh any resource and refactor the code accordingly from https://issues.jboss.org/browse/JBIDE-19822

**Comment by adietish** [comment]
ok, I can see the 2nd refresh that's required at times. I'll file a jira tomorrow and merge this for now

**Comment by adietish** [comment]
rebased, merged and pushed to upstream/master

**Pull request closed without merging**
