### PR TITLE
JBIDE-19162 clean up category.xml >> master

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by fbricon** [comment]
https://issues.jboss.org/browse/JBIDE-19162 is already closed. Is this PR still relevant ? My guts say no

**Comment by adietish** [comment]
I see this PR removing descriptions etc. Is this something we want to do?

**Comment by nickboldt** [comment]
If you want simpler XML, yes. If you like unnecessary long XML, no.  

Your choice.

**Comment by robstryker** [comment]
This PR is out of date.  There's new features.  But I think it's a good effort bc the category.xml is pretty messy.  I'd suggest this PR gets rejected and closed, or updated to pushed.  No reason to let this issue linger here.

**Pull request closed without merging**
