### PR TITLE
[JBIDE-21187] making sure we required tree ownerdraw fixedtree ownerd…

### PR DESCRIPTION
**Pull request by adietish**
…raw fixed org.eclipse.swt 3.104.1

### CODE REVIEW

**Comment by maxandersen** [comment]
this PR is incomplete now, right?

**Comment by adietish** [comment]
Yes, incomplete. It's currently only removing the workaround which makes it functional on Mars.1 only. It's missing the logical switch which would use the workaround in Mars.0 while not using it in Mars.1

**Comment by fbricon** [comment]
is this still relevant for JBT 4.4?

**Comment by adietish** [comment]
outdated, closing

**Pull request closed without merging**
