### PR TITLE
[JBIDE-22649] - When importing an OS2 app, the Git import does not use the default import folder used while importing OS3

### PR DESCRIPTION
**Pull request by jeffmaury**
- Use common dialog settings to store the Git repo value

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
LGTM but I think we could add some junit tests here to prevent future regressions

**Comment by adietish** [comment]
looks ok to me. The only question I have is why not use preferences vs dialog settings to store the default repo path. Typically you'd store UI settings in DialogSettings while here we have a more core-alike setting that would equally well fit into prefs (and could therefore be exposed in the preferences).

**Comment by adietish** [comment]
testPR

**Comment by jeffmaury** [comment]
Dialog settings is implemented on top of preferences but I remember you got added value using it (dialog size) but not sure it is relevant for wizards

**Comment by adietish** [comment]
@jeffmaury are you sure about dialog settings being stored to preferences? http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fdialogs_settings.htm talks of xml files (memento as far as I can remember - which is distinct from preferences, but I could be wrong).
Anyway, I'm not against using dialog settings but the value store here feels more like a candidate for preferences to me.

**Comment by jeffmaury** [comment]
You are right, dialog setting uses it's own serialization format (probably for compatibility reasons) and is saved in the workspace.

**Comment by fbricon** [comment]
It doesn't work for OpenShift 2 apps. Even though the stored path is loaded in the express wizard constructor, the default value is still displayed in the UI: http://screencast.com/t/SG4CFbotk

**Pull request merged**
