### PR TITLE
JBIDE-26653 Sonar settings update

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
Should be merged after: https://github.com/jbosstools/jbosstools-build/pull/289

**Comment by robstryker** [comment]
@jkopriva  is this still a good patch?  Upstream dependent patch was never committed.

**Comment by jkopriva** [comment]
@robstryker Thanks for reminding this to me, I have commented upstream issue. Please comment ;)

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jkopriva this PR currently fails with the following error:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.jboss.tools.openshift.ui.bot.test 3.7.0.qualifier
[ERROR]   Missing requirement: org.jboss.tools.openshift.ui.bot.test 3.7.0.qualifier requires 'osgi.bundle; org.eclipse.egit.ui.smartimport 4.8.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.jboss.tools.openshift.tests:org.jboss.tools.openshift.ui.bot.test:3.7.0-SNAPSHOT @ /mnt/hudson_workspace/workspace/jbosstools-openshift-Pull-Request/itests/org.jboss.tools.openshift.ui.bot.test/pom.xml: See log for details -> [Help 1]
```
Dare to fix it so that we can have it merged at some point?

**Comment by jkopriva** [comment]
@adietish yes, I will look at it after upstream is merged. Thanks!

**Comment by sbouchet** [comment]
@adietish @jkopriva please also note that the build still uses the devstudio 12.12 (https://github.com/jbosstools/jbosstools-openshift/blob/23f3528d5a9f4a588b928ccbd0654c214c508e78/itests/org.jboss.tools.openshift.ui.bot.test/pom.xml#L112). so it should be modified after GA to use the latest released version ?

**Comment by adietish** [comment]
testPR

**Comment by jkopriva** [comment]
@adietish Hi, this will work after PR in build repo is merged. https://github.com/jbosstools/jbosstools-build/pull/289

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
@jkopriva : failing with some version check and sonar errors : 
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.4.0:compare-version-with-baselines (default) on project org.jboss.tools.openshift.client: Version have moved backwards for (org.jboss.tools.openshift.client/3.8.0.AM1-v20191202-0852). Baseline has 3.8.0.Final-v20191023-2130-B5591) with delta: 0.0.0 -> [Help 1]
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project openshift: Please provide compiled classes of your project with sonar.java.binaries property -> [Help 2]

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jkopriva build error was the flaky git test, should get back to green with a rerun. Can we move forward with this?

**Comment by jkopriva** [comment]
@adietish yes, if the build will be ok, we can merge this

**Comment by adietish** [comment]
@odockal done, thx!

**Pull request merged**
