### PR TITLE
JBIDE-24839 Fix OAuth connection in OpenShift ITests requirement

### PR DESCRIPTION
**Pull request by jkopriva**
JBIDE-24839 ITests refactoring for OAuth connection

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
green build: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift.itests/253/

**Comment by jkopriva** [comment]
@adietish can you please review, when you have time? There has been a lot of changes in requirements, can you please check it, if it is ok? Thank you :)

**Comment by odockal** [comment]
Consider use small prompts dialogs when running test suite from IDE using launcher. I am referring those launch file where you have <argument> elements, those will fails to user if he will not update them, right? This could be a solution :https://github.com/jbosstools/jbosstools-openshift/blob/master/itests/org.jboss.tools.cdk.ui.bot.test/launchers/CDKAllTestsSuite.launch#L35, though.. small thing...;)

**Comment by jkopriva** [comment]
@odockal thanks for the tip, but I will keep it as it is for now - it is not in previously included launch configuration.

**Comment by jkopriva** [comment]
@adietish thanks for review and approve :)

**Pull request merged**
