### PR TITLE
[JBIDE-22861] - Explorer: Pod is not refreshed (watch problem with new ohttp based rest client)

### PR DESCRIPTION
**Pull request by jeffmaury**
- Change max concurrent web socket calls to 1000

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jcantrill** [comment]
@jeffmaury does this resolve the issue you were experiencing?

**Comment by jeffmaury** [comment]
Yes it fixed the issue and we don't need that many projects are the limit of 10 is reached as soon as we have two projects.

**Comment by jeffmaury** [comment]
testPR

**Comment by fbricon** [comment]
testPR

**Pull request merged**
