### PR TITLE
JBIDE-27457: Create service silent if no catalog installed

### PR DESCRIPTION
**Pull request by sbouchet**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by sbouchet** [comment]
testPR

**Review by jeffmaury — APPROVED** [review]
LGTM. Tested again employee.openshift.com

**Comment by jeffmaury** [comment]
Just a side note. If there are no service available in the catalog, no UI is shown and nothing is reported to the user. Reproduced against CDK where I installed just the service catalog but no other brokers (template, automation)

**Comment by sbouchet** [comment]
> I installed just the service catalog but no other brokers (template, automa



> Just a side note. If there are no service available in the catalog, no UI is shown and nothing is reported to the user. Reproduced against CDK where I installed just the service catalog but no other brokers (template, automation)

Ok, i'll improve this in another issue.

**Pull request merged**
