### PR TITLE
[JBIDE-22916] - Deploy Docker Wizard: Deploying a docker image from OpenShift explorer does not fetch metadata

### PR DESCRIPTION
**Pull request by jeffmaury**
- Change decision between Config and ContainerConfig

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
@jcantrill can you check this, please

**Comment by jcantrill** [comment]
I don't recall if there is an associated test but could there be one to verify this?  Other then that LGTM

**Comment by jeffmaury** [comment]
test is document in the JIRA

**Comment by adietish** [comment]
This unfortunately still doesnt work for me if I paste the image name (ex. "docker.io/openshift/hello-openshift". It also doesnt work when I use "Browse" to select the image. It only works if I use "Search".

**Comment by adietish** [comment]
discussing this shows that pasting doesnt work because my image is in the local docker daemon. "Browse" and "Search" are expected not to work. Thus +1 assuming we do jiras for the remaining issues.

**Pull request merged**
