### PR TITLE
[JBIDE-23165] prevent DelegatingConnectionWizardPage from connecting erroneously

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by bdshadow** [comment]
[Andre](@adietish), i tried to create new application from OS explorer, by right-clicking on project and then went forward to Template Parameters page. Then i tried to go back and for some reason `getPreviousPage()` was null and that's why my action was represented as Direction.FORWARDS.

Futhermore, PageChangingEvent was caught a lot of more times and it was neither `isChangingToThisPage`, nor `isChangingFromThisPage`.
See the screencast attached to jira to be more clear: https://issues.jboss.org/secure/attachment/12410313/Wrong-direction-screencast.webm

**Comment by adietish** [comment]
@bdshadow I updated my PR and I believe that it now works correctly now. 
https://issues.jboss.org/secure/attachment/12410518/page-changing-context-menu.ogv
https://issues.jboss.org/secure/attachment/12410517/page-changing-new-wizard.ogv

**Comment by adietish** [comment]
testPR

**Comment by bdshadow** [comment]
testPR

**Comment by bdshadow** [comment]
+1
LGTM + build is successful locally
testPR works neither for nor for Andre here

**Pull request merged**
