### PR TITLE
[JBIDE-24415] displaying resource type as label in server ed

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury @bdshadow please review this small UI-only change for the server adapter editor

**Comment by bdshadow** [comment]
@adietish the same tests problems as in [previous pr](https://github.com/jbosstools/jbosstools-openshift/pull/1497#issuecomment-300195269). See the jenkins build

**Comment by adietish** [comment]
@bdshadow our EGit unit tests have a long history of being unstable at times. Nothing changed for us in EGit. So unless EGit changed we're back in misterious EGit failures again.

**Comment by adietish** [comment]
@bdshadow real test failures as ```in HumanReadableX509CertificateTest.shouldReportValidity ``` (vs issues on the new jenkins like in EGit unit tests) are fixed. Dare to review this before we freeze please?

**Comment by bdshadow** [comment]
testPR

**Comment by bdshadow** [comment]
have strange problems with building it locally:
```bash
[dbocharo@dbocharo jbosstools-openshift]$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[dbocharo@dbocharo jbosstools-openshift]$ git fetch upstream pull/1498/head:JBIDE-24415_andre
[dbocharo@dbocharo jbosstools-openshift]$ git checkout JBIDE-24415_andre
Switched to branch 'JBIDE-24415_andre'
[dbocharo@dbocharo jbosstools-openshift]$ mvn clean install -DskipTests
[INFO] Scanning for projects...
[WARNING] Could not transfer metadata org.jboss.tools:parent:4.4.4.Final-SNAPSHOT/maven-metadata.xml from/to jbosstools-server (${jbosstools-server-site}): Cannot access ${jbosstools-server-site} with type p2 using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Could not transfer metadata org.jboss.tools:parent:4.4.4.Final-SNAPSHOT/maven-metadata.xml from/to jbosstools-base (${jbosstools-base-site}): Cannot access ${jbosstools-base-site} with type p2 using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.jboss.tools:openshift:3.3.3-SNAPSHOT: Could not transfer artifact org.jboss.tools:parent:pom:4.4.4.Final-SNAPSHOT from/to jbosstools-server (${jbosstools-server-site}): Cannot access ${jbosstools-server-site} with type p2 using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 4, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jboss.tools:openshift:3.3.3-SNAPSHOT (/home/dbocharo/dev/openshift/jbosstools-openshift/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.jboss.tools:openshift:3.3.3-SNAPSHOT: Could not transfer artifact org.jboss.tools:parent:pom:4.4.4.Final-SNAPSHOT from/to jbosstools-server (${jbosstools-server-site}): Cannot access ${jbosstools-server-site} with type p2 using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 4, column 10: Cannot access ${jbosstools-server-site} with type p2 using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout p2 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by bdshadow** [comment]
@adietish `HumanReadableX509CertificateTest.shouldReportValidity` is still failing :( https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-openshift-Pull-Request/739/

**Comment by bdshadow** [comment]
Merging it as `HumanReadableX509CertificateTest.shouldReportValidity` isn't related to this PR. + build and tests run locally without errors.

**Comment by adietish** [comment]
@bdshadow thx for merging into both branches!

**Pull request merged**
