### PR TITLE
[JBIDE-22915] - Deploy Docker Image: Replication controller is not created for some images

### PR DESCRIPTION
**Pull request by jeffmaury**
- ImageStream is created with tag to mimic oc behavior

Signed-off-by: Jeff MAURY jmaury@redhat.com

### CODE REVIEW

**Comment by jcantrill** [comment]
Is there an associated test to validate this logic?  Also, we should confirm it works against both origin and enterprise releases as 'oc new-app' changed in this regards quite a lot over time and I have concerns it supporting this behavior over the range of versions we need to suport

**Comment by jeffmaury** [comment]
It's documented in the JIRA. You need to deploy the  docker.io/openshift/hello-openshift:v1.2.1 image

**Comment by adietish** [comment]
@jeffmaury @jcantrill This works for me using the steps in jira. I'd love to merge this and maybe file a jira   to make sure it works in enterprise and 1.2?

**Comment by adietish** [comment]
retested it using the steps in jira. replication controller "hello-openshift-1" was created. Works for me.

**Pull request merged**
