### PR TITLE
[JBIDE-26869,JBIDE-26915] try reconnecting to crc & use latest client 8.1.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury please review

**Comment by adietish** [comment]
@jeffmaury using the latest openshift-restclient-java is required for JBIDE-26869 & JBIDE-26915. Now that the change in the client required for JBIDE-26915 was merged at https://github.com/openshift/openshift-restclient-java/pull/414 we should have this merged, too. Please review

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury plase review and add /lgtm label

**Comment by jeffmaury** [comment]
I tested on Windows and seems to work although I did not get that connection error on my Windows laptop. However, I noticed that the UI freeze in certains conditions that I think are related to recent changes to the restclient.
I had a bunch of OpenShift connection defined in my workspace, to CDK or CRC clusters that are not started. When I select one of those connections, the UI freezes and I took a snapshot of the UI thread:

```
Name: main
State: RUNNABLE
Total blocked: 14  Total waited: 2 001

Stack trace: 
java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
   - locked java.net.DualStackPlainSocketImpl@536aab58
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
java.net.Socket.connect(Socket.java:589)
okhttp3.internal.platform.Platform.connectSocket(Platform.kt:126)
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:268)
okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:176)
okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
com.openshift.internal.restclient.okhttp.AuthenticatorInterceptor.intercept(AuthenticatorInterceptor.java:57)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:56)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
okhttp3.RealCall.execute(RealCall.kt:66)
com.openshift.internal.restclient.DefaultClient$RequestingSupplier.request(DefaultClient.java:612)
com.openshift.internal.restclient.DefaultClient$RequestingSupplier.requestIfRequired(DefaultClient.java:601)
com.openshift.internal.restclient.DefaultClient$RequestingSupplier.get(DefaultClient.java:596)
com.openshift.internal.restclient.DefaultClient.getOpenshiftMasterVersion(DefaultClient.java:456)
org.jboss.tools.openshift.core.connection.Connection.getOpenShiftMasterVersion(Connection.java:651)
org.jboss.tools.openshift.internal.ui.property.ConnectionPropertySource.getPropertyValue(ConnectionPropertySource.java:111)
org.eclipse.ui.views.properties.PropertySheetEntry.refreshValues(PropertySheetEntry.java:585)
org.eclipse.ui.views.properties.PropertySheetEntry.refreshChildEntries(PropertySheetEntry.java:543)
org.eclipse.ui.views.properties.PropertySheetEntry.setValues(PropertySheetEntry.java:729)
org.eclipse.ui.views.properties.PropertySheetViewer.setInput(PropertySheetViewer.java:979)
org.eclipse.ui.views.properties.PropertySheetPage.selectionChanged(PropertySheetPage.java:507)
org.jboss.tools.openshift.internal.common.ui.explorer.DefaultPropertySection.setInput(DefaultPropertySection.java:49)
org.eclipse.ui.views.properties.tabbed.TabContents$5.run(TabContents.java:184)
org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
org.eclipse.ui.internal.JFaceUtil$$Lambda$10/1776512995.run(Unknown Source)
org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
org.eclipse.ui.views.properties.tabbed.TabContents.setInput(TabContents.java:187)
org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage$SelectionChangedListener.selectionChanged(TabbedPropertySheetPage.java:221)
org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
org.eclipse.ui.internal.JFaceUtil$$Lambda$10/1776512995.run(Unknown Source)
org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2118)
org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1170)
org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1199)
org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:237)
org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:402)
org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:780)
org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyList.select(TabbedPropertyList.java:844)
org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyViewer.setSelectionToWidget(TabbedPropertyViewer.java:134)
org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1697)
org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1653)
org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:376)
org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.setInput(TabbedPropertySheetPage.java:763)
org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.selectionChanged(TabbedPropertySheetPage.java:571)
org.eclipse.ui.views.properties.PropertySheet.showSelectionAndDescription(PropertySheet.java:569)
org.eclipse.ui.views.properties.PropertySheet.selectionChanged(PropertySheet.java:549)
org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:240)
org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:119)
org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:74)
org.eclipse.ui.internal.e4.compatibility.SelectionService$$Lambda$177/824096549.selectionChanged(Unknown Source)
org.eclipse.e4.ui.internal.workbench.SelectionAggregator$3.run(SelectionAggregator.java:163)
org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyPostListeners(SelectionAggregator.java:160)
org.eclipse.e4.ui.internal.workbench.SelectionAggregator.access$7(SelectionAggregator.java:158)
org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.lambda$0(SelectionAggregator.java:250)
org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6$$Lambda$603/1413154179.run(Unknown Source)
org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
   - locked org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6@3848c63
org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.changed(SelectionAggregator.java:250)
org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setPostSelection(SelectionServiceImpl.java:39)
org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$2(CompatibilityPart.java:128)
org.eclipse.ui.internal.e4.compatibility.CompatibilityPart$$Lambda$289/101264705.selectionChanged(Unknown Source)
org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:818)
org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
org.eclipse.ui.internal.JFaceUtil$$Lambda$10/1776512995.run(Unknown Source)
org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:815)
org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1185)
org.eclipse.ui.navigator.CommonViewer.handlePostSelect(CommonViewer.java:460)
org.eclipse.jface.viewers.StructuredViewer.lambda$0(StructuredViewer.java:1208)
org.eclipse.jface.viewers.StructuredViewer$$Lambda$301/119819655.accept(Unknown Source)
org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:263)
org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:258)
org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:428)
org.eclipse.jface.util.OpenStrategy$1$$Lambda$602/246583097.run(Unknown Source)
org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
   - locked org.eclipse.swt.widgets.RunnableLock@766e7e7f
org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961)
org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588)
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
org.eclipse.ui.internal.Workbench$$Lambda$27/408544604.run(Unknown Source)
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
org.eclipse.equinox.launcher.Main.run(Main.java:1468)
org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```

Not sure why the connect would be that long but this is clearly a regression

**Comment by adietish** [comment]
@jeffmaury thx for testing, ok, will look into it

**Comment by adietish** [comment]
@jeffmaury impl'd async loading of the cluster properties (kubernetes- & openshift-versions) which caused the freeze you were experiencing. Please re-review

**Comment by jeffmaury** [comment]
testPR

**Comment by adietish** [comment]
deployed artifact to https://repository.jboss.org/nexus/service/local/repositories/snapshots/content/com/openshift/openshift-restclient-java/8.1.1-SNAPSHOT/openshift-restclient-java-8.1.1-20200122.214411-10.jar

**Pull request merged**
