### PR TITLE
[JBIDE-20464] opening oauth login in ext. browser (not dialog) in MacOS

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@fbricon pls review

**Comment by fbricon** [comment]
Couldn't we just get the response of the token url into a string, then parse it to extract the token (response.substring(indexOf("--token="), indexOf(<following space>)), put it directly into the textbox?

**Comment by adietish** [comment]
@fbricon nope since the user still has to do the oauth login/auth in the browser (RH SSO in our stg server)

**Comment by fbricon** [comment]
Applied in master

**Pull request closed without merging**
