### PR TITLE
JBIDE-22362: Enabling DEV_MODE by default for Node.js projects

### PR DESCRIPTION
**Pull request by ibuziuk**
# Pull Request Checklist
## General
QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
@adietish @mlabuda please review

While testing smth. there is an error on setting DEV_MODE variable: 
image

Do you happen to know why this is happening ? for setting varible I use similar approach as for "Manage Environment Variables.." dialog

**Comment by jcantrill** [comment]
This happens because your DC is stale.  Either the watch did not detect it was changed from under you or maybe you were in mid flight when it changed.  It would be nice if we could provide a more friendly error as to what is happing.

**Comment by ibuziuk** [comment]
@jcantrill hmmm... I am trying to schedule job for setting DEV_MODE on server adapter startup - https://github.com/jbosstools/jbosstools-openshift/pull/1370/commits/b8cef66c0511abc2a897473a75bfebd4f1c22171#diff-6e935156a26963d78785b59aaa48cabeR132 Is there a better place to set it in order to make sure that DC is up-to-date ?

**Comment by jcantrill** [comment]
@ibuziuk presumably you should also have the latest version of the DC, but maybe it is in your best interest to always fetch a copy to ensure you have the latest.

**Comment by adietish** [comment]
@ibuziuk I would get the DC in the latest possible moment, and select the most recent version of it. I had a similar issue when scaling. I had to select the replication controller that was referrring to the latests DC. I did that via the following utils method: https://github.com/adietish/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java#L364
I assume that this isnt what you need but could help to frame the idea.

**Comment by adietish** [comment]
@ibuziuk we're closing in on a freeze for 4.4.2.Final this Thursday. Any chance we could be lucky and get this in before? Would be awesome.

**Comment by ibuziuk** [comment]
@adietish I had to switch to eclipse che work now. Regarding this PR - I can not understand why DC is stale and what exactly should be done to avoid it. 
@alexeykazakov there are two open issues regarding Node.js debugger that are targeted to 4.4.2.Final - this one and JBIDE-23422. It is not clear how those should be tackled. Please, advice

**Comment by alexeykazakov** [comment]
I can confirm that Ilya is focusing on Che work now and can't spent enough time on OpenShift issues. @adietish @jeffmaury please take care of the remaining issues. If not enough time for 10.2 then let's just move them to 10.3.

**Comment by adietish** [comment]
@ibuziuk I can't replicate your failure, but I face a different issue:
If I stop and start the server adapter, it keeps waiting for the pod in DeploymentConfigListenerJob until it times out. The weird part is that the adapter seems to think that's it restarting from debug, but it isnt. I launched a fresh Eclipse instance.

**Comment by adietish** [comment]
The reason why I see the adapter trying to turn off debugging even when I'm not restarting from debugging is the following:
https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugUtils.java#L207:
```debugContext.setDebugEnabled(Boolean.parseBoolean(debugEnabled) || Boolean.parseBoolean(devModeEnabled));```
@ibuziuk Do you know why?
@fbricon according to git you're the author of the above. Can you provide insights on the reasoning behind this?

**Comment by fbricon** [comment]
@adietish IIRC, I had to test 2 variables because there was an inconsistency between NodeJS and Java based images

**Comment by ibuziuk** [comment]
> debugContext.setDebugEnabled(Boolean.parseBoolean(debugEnabled) || Boolean.parseBoolean(devModeEnabled));
@adietish unfortunately, have no idea

**Comment by adietish** [comment]
Here's the stacktrace for the above error:
```
com.openshift.restclient.OpenShiftException: Exception trying to PUT https://10.1.2.2:8443/oapi/v1/namespaces/nodejs/deploymentconfigs/nodejs-example response code: 409 Operation cannot be fulfilled on deploymentconfigs "nodejs-example": the object has been modified; please apply your changes to the latest version and try again
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:114)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:65)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:217)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:194)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:183)
	at com.openshift.internal.restclient.DefaultClient.update(DefaultClient.java:275)
	at org.jboss.tools.openshift.core.connection.Connection.updateResource(Connection.java:451)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController$1.run(OpenShiftLaunchController.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by jeffmaury** [comment]
Closed because rebased in #1412

**Pull request closed without merging**
