### PR TITLE
[JBIDE-25506] fixes .git exclusion filter when rsync'ing

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
this depends on https://github.com/openshift/openshift-restclient-java/pull/317

**Comment by adietish** [comment]
@jkopriva is it possible for you to verify this? You'd need to 1st build a new client library and then build this PR.

**Comment by jkopriva** [comment]
@adietish sure, I will do it today/tomorrow

**Comment by adietish** [comment]
@jkopriva great, thx!

**Comment by jkopriva** [comment]
@adietish LGTM, it works as expected on Win10 and F27.

**Comment by adietish** [comment]
@jkopriva thx!

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
please +1 for a preliminary fix that correctly wont rsync .git

**Comment by jkopriva** [comment]
+1

**Pull request merged**
