### PR TITLE
[JBIDE-25172] - default profile and 'cdk' file wont exist if specific…

### PR DESCRIPTION
**Pull request by robstryker**
… profile was setup

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by robstryker** [comment]
This needs more work

**Comment by robstryker** [comment]
This patch solves JBIDE-25172 and JBIDE-25170. 

JBIDE-25170 is the issue where an empty profile tag should still send '--profile minishift' to the command line arguments, in case the user has changed the default profile of the system. 

JBIDE-25172 fixes the adapter being unable to locate credentials when a user has a fresh cdk3.2 install and chooses to set up only a specific profile (./minishift setup-cdk --profile test555)  and never sets up the default profile. In this case, ~/.minishift/cdk file will not exist, and the adapter must instead look for ~/.minishift/profiles/test555/cdk

These two patches are closely related to each other and cannot be committed separately without refactoring the two patches. I prefer to squash them and commit them as an indivisible group.

**Comment by adietish** [comment]
I can replicate the issue without the suggested changes in code. Now testing with the PR.

**Comment by adietish** [comment]
the PR is fixing the usecase as described in jira.

**Comment by adietish** [comment]
@robstryker I am wondering why the server adapter wizard nows suggests by default the "minishift" profile?

**Comment by adietish** [comment]
The other usecase discussed with @robstryker also works for me:

* EXEC: setup-cdk  without a profile
* EXEC: setup-cdk with --profile test
* ASSERT: make sure test is the active profile: ```minishift profile set test```. ```minishift  profile list``` shows that test is the active profile
* EXEC: in Eclipse try to launch a cdk server adapter that has no profile set. 

**BEFORE THE PR**
Profile **test** is launched

**AFTER THE PR**
Profile **minishift** (the default profile) is launched.

**Pull request merged**
