### PR TITLE
jbide-24797 - apply default Eclipse code formatter

### PR DESCRIPTION
**Pull request by bdshadow**
Signed-off-by: Dmitrii Bocharov <dbocharo@redhat.com>

Here is the default eclipse formatting applied by the [formatter-maven-plugin](http://code.revelc.net/formatter-maven-plugin/formatter-maven-plugin/).

The main changes are here in pom.xml:https://github.com/jbosstools/jbosstools-openshift/pull/1559/files#diff-600376dffeb79835ede4a0b285078036R41

You can compare it with a slightly different formatting profile: https://github.com/jbosstools/jbosstools-openshift/pull/1560

### CODE REVIEW

**Comment by bdshadow** [comment]
testPR

**Comment by bdshadow** [comment]
testPR

**Comment by adietish** [comment]
@bdshadow want to rebase this please?

**Comment by bdshadow** [comment]
@adietish @robstryker rebased

**Comment by bdshadow** [comment]
@adietish @robstryker could you, please, merge it?

**Comment by robstryker** [comment]
Opened https://github.com/jbosstools/jbosstools-openshift/pull/1639  after fixing the 2 changed files. My goal is to get this pushed asap.

**Comment by robstryker** [comment]
This has been pushed in the other PR.

**Pull request closed without merging**
