### PR TITLE
[JBIDE-18866] Allow SSH git URLs for app-code and downloadable carts

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
this was merged, closing.

**Comment by alexeykazakov** [comment]
This PR has been merged into master only. It has NOT been merged into 4.2.x - https://github.com/jbosstools/jbosstools-openshift/commits/jbosstools-4.2.x

**Comment by adietish** [comment]
@alexeykazakov thx for noticing! reopening

**Comment by adietish** [comment]
merged

**Pull request merged**
