### PR TITLE
[JBIDE-22197] - Icon in template Details of Local Template is not loaded for some templates file

### PR DESCRIPTION
**Pull request by jeffmaury**
- Just adding a PNG for Java
- No code modification as strack trace is generated once for a specific file and thus caught by Aeri

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
Can you add a screenshot of how it looks like in Eclipse?
I'm pretty sure the webconsole would use another icon, have you checked?

**Comment by jeffmaury** [comment]
Eclipse UI:


Web Console:

**Comment by jcantrill** [comment]
All icons we use that are displayed are the same as provided by the web console.  Most are sourced from the patterfly project and others were given to me.  I will see if i can source the actual file used and we can check it in as a resource to our repo.

**Comment by fbricon** [comment]
Inspecting the web console, I found an openjdk icon:

**Comment by jcantrill** [comment]
https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.ui/icons/apps/openjdk.png

**Comment by fbricon** [comment]
ok, so we probably just need to copy openjdk.png to java.png (we need both)

**Comment by jeffmaury** [comment]
Agree. Wil do.

**Pull request merged**
