### PR TITLE
JBIDE-25303 - Provide hot deploy for SpringBoot starter app on OpenShift

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
it requires to have the code from this PR in Jboss Tools Server: https://github.com/jbosstools/jbosstools-server/pull/548

**Comment by apupier** [comment]
this part seems to work, now need to find how to workaround https://github.com/openshift/openshift-restclient-java/issues/300

Do you have already some tests launching an OpenShift instance and deploying apps to check it "for real"?

**Comment by apupier** [comment]
another thing to look, i'm not sure what to look for is that I have this stacktrace logged:
```
!MESSAGE Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.getSubsystemMappingForCreation(SubsystemModel.java:409)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:460)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:362)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:342)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ServerProfileModel.getController(ServerProfileModel.java:190)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ProfileServerBehavior.getController(ProfileServerBehavior.java:59)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ProfileServerBehavior.getModuleStateController(ProfileServerBehavior.java:32)
	at org.jboss.tools.openshift.core.server.OpenShiftServerBehaviour.launchPostStartupJobs(OpenShiftServerBehaviour.java:58)
	at org.jboss.tools.openshift.core.server.OpenShiftServerBehaviour.setServerStarted(OpenShiftServerBehaviour.java:37)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.setServerState(OpenShiftLaunchController.java:224)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.launch(OpenShiftLaunchController.java:105)
	at org.jboss.ide.eclipse.as.wtp.core.server.launch.ControllableServerLaunchConfiguration.launch(ControllableServerLaunchConfiguration.java:52)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:731)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3566)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3502)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:377)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
!SUBENTRY 1 org.jboss.ide.eclipse.as.wtp.core 4 0 2017-11-09 13:33:15.651
!MESSAGE Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
```

**Comment by jeffmaury** [comment]
Yes there are some integration tests but I think they are based on the EAP builder images and quick starts (has we need a project to be available from the OpenShift cluster thus hosted on Github for example)

**Comment by adietish** [comment]
i see the very same error like @apupier when publishing:
image
```
org.eclipse.core.runtime.CoreException: Unable to choose a subsystem. Multiple subsystems found for servertype org.jboss.tools.openshift.server.type and system type modules
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.getSubsystemMappingForCreation(SubsystemModel.java:409)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:460)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:362)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.SubsystemModel.createSubsystemController(SubsystemModel.java:342)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ServerProfileModel.getController(ServerProfileModel.java:190)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ProfileServerBehavior.getController(ProfileServerBehavior.java:59)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.ProfileServerBehavior.getModuleStateController(ProfileServerBehavior.java:32)
	at org.jboss.tools.openshift.core.server.OpenShiftServerBehaviour.launchPostStartupJobs(OpenShiftServerBehaviour.java:58)
	at org.jboss.tools.openshift.core.server.OpenShiftServerBehaviour.setServerStarted(OpenShiftServerBehaviour.java:37)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.setServerState(OpenShiftLaunchController.java:224)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.launch(OpenShiftLaunchController.java:105)
	at org.jboss.ide.eclipse.as.wtp.core.server.launch.ControllableServerLaunchConfiguration.launch(ControllableServerLaunchConfiguration.java:52)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:731)
	at org.eclipse.wst.server.core.internal.Server.startImpl2(Server.java:3566)
	at org.eclipse.wst.server.core.internal.Server.startImpl(Server.java:3502)
	at org.eclipse.wst.server.core.internal.Server$StartJob.run(Server.java:377)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by adietish** [comment]
The error is caused by missing subsystem declarations in the plugin.xml. The complete serverProfile should be:
```
       <serverProfile
             id="openshift3.springboot"
             serverTypes="org.jboss.tools.openshift.server.type">
          <subsystem
                subsystem="publish.rsync.filesystem.springboot"
                system="publish" />
         <subsystem
               subsystem="moduleDeployPath.xmlprefs.openshift"
               system="moduleDeployPath" />
         <subsystem
               subsystem="modules.noop.default"
               system="modules" />
          <description
                description="A profile configured to publish to a local folder and rsync to a remote OpenShift pod based on SpringBoot starter."
                name="openshift3.springboot">
          </description>
       </serverProfile>
```
@robstryker thoughts?

Once this is corrected, there are no publishing errors any more.
But then, changes dont seem to be propagated, neither when changing xml nor code. Publishing is triggered though. Need to investigate.

**Comment by adietish** [comment]
weird enough, the changes in code are always transferred but wont get always activated. So we still have a problem, Huston....

**Comment by adietish** [comment]
debugging isn't working either. The port forwarding is successfully started, but the local debugger cannot connect to the debug port on the pod.
image

**Comment by apupier** [comment]
> @apupier do you know the correct port to debug the app? Can you make sure that the image contains the correct annotation?

it seems that the debug port is specified with a different value "JAVA_DEBUG_PORT": https://hub.docker.com/r/fabric8/s2i-java/

I would say that it is a better practice to specify which kind of Debug port we are talking about. What do you think to support the JAVA_DEBUG_PORT variable?

**Comment by apupier** [comment]
> It also doesnt look like the app is launched so that it accepts debugger connections. With the above debugging env var java is being launched with the following arguments which are missing the debugging instructions (https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-running-as-a-packaged-application tells you to use --debug)

seems that the image is using JAVA_ENABLE_DEBUG https://hub.docker.com/r/fabric8/s2i-java/

**Comment by adietish** [comment]
@apupier so to me it looks like the missing link are the docker labels that provide the keys (and default values) to enable the debug mode on a given port (the following is as it's provided in the nodejs docker images that we use. Analogous values exist for the eap images etc.).
```
"com.redhat.deployments-dir": "/opt/app-root/src",
"com.redhat.dev-mode": "DEV_MODE:false",
"com.redhat.dev-mode.port": "DEBUG_PORT:5858",

```
(for both debug labels the format is as follows: <env key-name>:<default value>).
I commented this in your jira issue here: https://issues.jboss.org/browse/OSFUSE-548?focusedCommentId=13493632&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13493632

**Comment by adietish** [comment]
@apupier btw. when manually providing the correct values (provided at https://hub.docker.com/r/fabric8/s2i-java/) debugging works!

image

**Comment by adietish** [comment]
replaced by #1635

**Pull request closed without merging**
