### PR TITLE
[JBIDE-22111] removed stdout from log4j so that client log wont make it to Eclipse log

### PR DESCRIPTION
**Pull request by adietish**
…

### CODE REVIEW

**Comment by adietish** [comment]
@fbricon @jcantrill plz review

**Comment by fbricon** [comment]
Works as advertised. 
+1 to apply in master
Waiting for green light to apply to 4.3.x (cc @alexeykazakov @maxandersen)

**Comment by alexeykazakov** [comment]
+ 1 for both master and 4.3.x to include into respin

**Comment by adietish** [comment]
merged into jbosstools-4.3.x and cherry-picked into master

**Pull request merged**
