### PR TITLE
JBIDE-26532 Fix for update UI when copying login command with different

### PR DESCRIPTION
**Pull request by jkopriva**
tokens

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
@adietish @odockal Can you please retest? I have tried it on Win10 and F29 and it was working.

**Comment by jkopriva** [comment]
@adietish Thank you for retest!

**Comment by odockal** [comment]
@jkopriva Works for me too. My fedora is behaving right in this matter. +1

**Pull request merged**
