### PR TITLE
jbide-23470: Server Adapter: stuck restarting in debug mode

### PR DESCRIPTION
**Pull request by bdshadow**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? no

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jeffmaury** [comment]
Works better. Run several times the following sequence:

- Restart in Debug mode
- Restart

However, I have almost always an error when Restarting during the publish phase:
image

**Comment by bdshadow** [comment]
@jeffmaury the problem is that you have to wait, while the previous process is finished. You can bump into this error if you do almost any 2 actions immediately one after another. In order to avoid it, wait until the new Pod is created and running.

I suppose we should think about disabling the ability to run\start\debug server adapter until the process, described above, is finished.

**Comment by jeffmaury** [comment]
I don't follow you because I waited until the previous phase was finished but will check if waiting more will fix that

**Comment by jeffmaury** [comment]
See the video capture: https://youtu.be/oc9yKvG_h1o

**Comment by bdshadow** [comment]
@jeffmaury thank you! Will work on it

**Comment by adietish** [comment]
@bdshadow you might also want to correct the JBIDE in the correct number JBIDE-23740 -> JBIDE-23470

**Comment by adietish** [comment]
@bdshadow +1 on the suggestion to disable run/start/debug while the new pod is not ready

**Comment by adietish** [comment]
@bdshadow @jeffmaury I tried with existing and new app. I could restart the adapter flawlessly in both cases. I can also restart the adapter from debugging and it works flawlessly, I dont get the error that you screencasted.

**Comment by adietish** [comment]
We really should unit-test the WatchManager. It proved to be a complex and sensitive component and thus it is highly required to have unit-tests for it. I'll jira

**Comment by jeffmaury** [comment]
@adietish  this was tested on Win10 with oc 1.3.0 and CDK 2.2

**Comment by bdshadow** [comment]
tested on 
OS: windows 10
cdk: CDK-2.2-GA from 2016-09-16
box: rhel-cdk-kubernetes-7.2-29.x86_64.vagrant-virtualbox.box

could reproduce this issue randomly from time to time. Sometimes the same order of actions works fine, and on the next try stuck again =(

**Comment by bdshadow** [comment]
@jeffmaury @adietish 
I've just tested 10 times in a row, but couldn't replicate it. During the whole day the server apater got stuck only 2 times.
@jeffmaury anyway, what i wrote in previous comment is not the error, which you "screencasted\screenshotted" above. It was exactly the issue described in JIRA, and i think it is connected that WatchManager wasn't started for some reason. The solution is just to refresh the project in OS explorer - it's described in Workaround section in JIRA.

So in my opinion we should merge this fix (of course if you don't have any other objections) and change priority of the JIRA  from Critical to Major, because the code freeze is the next week and i have PTO during the whole week. 

It would also be great if smb could test it on Windows some times more.

**Comment by jeffmaury** [comment]
Close as #1375 is an update

**Pull request closed without merging**
