### PR TITLE
[JBIDE-20455] open oc file chooser at location set in "oc location"

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@fbricon pls review

**Comment by fbricon** [comment]
Browse location is properly initialized

One weird thing though: if you select a file, then change the value in the textbox, to something non-existant, validation doesn't occur when losing focus. when re-entering focus then, validation kicks in

**Comment by adietish** [comment]
I noticed the weirdness but didnt find a solution in a reasonable fashion

**Comment by adietish** [comment]
merged and pushed to upstream/master

**Pull request merged**
