### PR TITLE
JBIDE-23039 - an interactive terminal solution for all three operating major OS types

### PR DESCRIPTION
**Pull request by robstryker**
Test patch to see if cdt.native works to fix the issue for windows and mac. 

This patch isn't suitable for merging and needs cleaning up. It's actually the same patch as before with just 3 or 4 lines changed, but since I've already reverted the original, the patch seems longer.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
testPR

**Comment by alexeykazakov** [comment]
testPR

**Comment by alexeykazakov** [comment]
@nickboldt @mickaelistria any idea why PR checks are not triggered for this PR?

**Comment by mickaelistria** [comment]
No clue so far. Did any PR from @robstryker ever managed to get verified by the PR job for OpenShift? I remember several issue specifically for this user. Is he correctly part of the various teams on GitHub? Is he not blacklisted somewhere?

**Comment by nickboldt** [comment]
I've explicitly added robstryker to the admin and white lists for the job.

**Comment by nickboldt** [comment]
testPR

**Comment by robstryker** [comment]
testPR

**Comment by mmalina** [comment]
@robstryker , the latest commit works for me on Mac - no longer is the output mixed between Console and Terminal, now it only uses Terminal and I can successfully enter my credentials.

**Pull request merged**
