### PR TITLE
[JBIDE-26815] fix compilation error in egit tests

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by sbouchet** [comment]
build fails becuse it seems it gets the wrong version from the tp. checking.

**Comment by adietish** [comment]
@sbouchet is the TP missing in the repos? Using the latest TP in Eclipse has this compiling while tycho is complaining about an override that has no super method to override:
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-openshift-Pull-Request/2098/console
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.4.0:compile (default-compile) on project org.jboss.tools.openshift.egit.test: Compilation failure: Compilation failure: 
[ERROR] /mnt/hudson_workspace/workspace/jbosstools-openshift-Pull-Request/tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/MockSystemReader.java:[197] 
[ERROR]     public StoredConfig getUserConfig()
[ERROR]             throws IOException, ConfigInvalidException {
[ERROR]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method getUserConfig() of type MockSystemReader must override or implement a supertype method
[ERROR] /mnt/hudson_workspace/workspace/jbosstools-openshift-Pull-Request/tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/MockSystemReader.java:[203] 
[ERROR]     public StoredConfig getSystemConfig()
[ERROR]             throws IOException, ConfigInvalidException {
[ERROR]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method getSystemConfig() of type MockSystemReader must override or implement a supertype method
[ERROR] 2 problems (2 errors)
[ERROR] -> [Help 1]
```
Am I missing something?

**Comment by sbouchet** [comment]
Newer TP is needed, please wait for https://github.com/jbosstools/jbosstools-target-platforms/pull/331 to be merged before retrying to fix.

**Comment by sbouchet** [comment]
testPR

**Comment by adietish** [comment]
pushed a version where I removed the MockSystemReader, using the one supplied by jgit.junit.

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Pull request merged**
