### PR TITLE
[JBIDE-25504] publish dependency as child-module

### PR DESCRIPTION
**Pull request by adietish**
depends on PR for central at [#420](https://github.com/jbosstools/jbosstools-central/pull/420), which has to be merged first.

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
retest this please

**Comment by adietish** [comment]
testPR

**Comment by nickboldt** [comment]
testPR

**Comment by psrna** [comment]
I appreciate the energy you are giving to bring this feature to life. However I honestly think that this is a serious risk for the release. Mainly because this is the GA sprint, we have zero time to fix if something is wrong, it is after CF and it is new feature with 18commits in a feature frozen sprint. When we talked about it during sprint planning the deal was that you merge it very early in the sprint. It has not happened (and I understand the reasons), but that also means this feature is completely untested. Giving -1.

**Comment by nickboldt** [comment]
-1, PR job is STILL red. Also adding new features after feature freeze 3 weeks ago is highly discouraged. Recommend slipping this to the AM1 sprint of JBT 4.6, so QE has the requisite time to test and shake the problems out.

**Comment by jeffmaury** [comment]
Delayed

**Comment by adietish** [comment]
@jkopriva can you please test this new feature? 

* First checkout the PR to jbosstools-central: https://github.com/jbosstools/jbosstools-central/pull/420
* get the zip that's attached to https://issues.jboss.org/browse/JBIDE-25504. It contains 2 projects: 
  * fuse-on-openshift (spring-boot project)
  * penguins (dependency for fuse-on-openshift)
* build and install penguins (mvn clean install)
* deploy fuse-on-openshift: 
```
mvn clean install fabric8:deploy \
-Dkubernetes.master=<openshift server> \
-Dkubernetes.namespace=<openshift project> \
-Dkubernetes.auth.basic.username=developer \
-Dkubernetes.auth.basic.password=developer \
-Dfabric8.mode=openshift \
-Dkubernetes.trust.certificates=true \
-Dfabric8.build.strategy=s2i \
-Dkubernetes.auth.tryServiceAccount=false \
-Dfabric8.generator.from=fabric8/s2i-java \
-Dfabric8.generator.fromMode=docker \
-Dkubernetes.auth.tryKubeConfig=false
```
* import both projects into Eclipse
  * import both maven projects at once
  * import fuse-on-openshift first, then penguins
  * import penguins first, then fuse-on-openshift
* create a server adapter for fuse-on-openshift (camel-ose-springboot-xml)
* open "Pod Log" for the pod that's running the app, inspect the log output
* change a class in fuse-on-openshift, verify that changes were synced upstream and are visible in the log output
* change Pingu in penguins, verify that changes were synced upstream and are visible in the log output

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
@adietish I have tried to follow your steps, it was working, but I did get some errors when syncing(but app was working and correctly changed): 
eclipse.buildId=12.0.0.AM2-v20180521-0109-B2508
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -product com.jboss.devstudio.core.product -data /home/jkopriva/devstudio_B2508/workspace/../runtime-EclipseApplication -dev file:/home/jkopriva/devstudio_B2508/workspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

org.jboss.tools.openshift.core
Error
Mon May 21 09:23:36 CEST 2018
OpenShiftBinaryCapability process exited: rsync: chgrp "/deployments/BOOT-INF/." failed: Operation not permitted (1)
rsync: chgrp "/deployments/BOOT-INF/classes" failed: Operation not permitted (1)
rsync: chgrp "/deployments/BOOT-INF/classes/org" failed: Operation not permitted (1)
rsync: chgrp "/deployments/BOOT-INF/classes/org/mycompany" failed: Operation not permitted (1)
rsync: chgrp "/deployments/BOOT-INF/classes/spring" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
error: exit status 23

**Comment by adietish** [comment]
@jkopriva thx for testing. The above error is what you discovered in https://issues.jboss.org/browse/JBIDE-25700, which is a problem in the oc binary that should be fixed in upcoming versions of the oc binary. See https://github.com/openshift/origin/issues/19365
If other than this error things work, I'd suggest that we merge.
@jeffmaury +1?

**Comment by jkopriva** [comment]
@adietish ok, I thought I have seen this, then from my side +1

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Pull request merged**
