### PR TITLE
JBIDE-25049 JBIDE-25046 - fixes to discovering registry url

### PR DESCRIPTION
**Pull request by robstryker**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by robstryker** [comment]
What the heck is this... build error.

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project openshift: SonarQube is unable to analyze file : '/mnt/hudson_workspace/workspace/jbosstools-openshift-Pull-Request/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java': NullPointerException -> [Help 1]

Rest of  build seems fine.  weird.

**Comment by robstryker** [comment]
testPR

**Comment by adietish** [comment]
sonar is failing to analyze this code with an NPE:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project openshift: SonarQube is unable to analyze file : '/mnt/hudson_workspace/workspace/jbosstools-openshift-Pull-Request/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java': NullPointerException -> [Help 1]
```
Looks like a bug in sonar. @bdshadow @jeffmaury do you know how to include -X in the sonar job so that we get more details and can file a bug to sonar?

**Comment by adietish** [comment]
I reported the NPE that we have in Sonar to the mailing-list: https://groups.google.com/forum/?hl=en#!topic/sonarqube/t7-A4M_Ohd0
See https://github.com/jbosstools/jbosstools-openshift/pull/1568

**Comment by adietish** [comment]
regarding the issue in JBIDE-25046 i now have the following behaviour:
1. When I launch the cdk:
* the 2nd connection for "developer" is updated to hold the reg url
* the 1nd connection for "admin" isnt
2. When I manually hit "Discover" in the connection for "admin", the registry url is inserted.
Seems to work as suggested in jira. 
@robstryker why only update 1 connection, why not all connection to the same cdk?

**Comment by adietish** [comment]
@robstryker then when trying to discover a registry that already is filled-in, there is no detection that the discovered url matches the existing one, so no change is required:
image

**Comment by adietish** [comment]
the updated code now wont replace an existing registry url with an identical one. It does nothing, no dialog, as one would expect. nice.

**Comment by adietish** [comment]
so once the DCO check passes (2nd commit does not have signed-off, not sure how it does merge and what it preseves) I guess you can merge this. +1
Then there's this other question: assuming we have 2 connections (1 for admin, 1 for developer), why are we only updating 1 connection (the one for developer in my case) and not both (the one for admin isnt updated with a registry url)?

**Pull request merged**
