### PR TITLE
JBIDE-20296 Appending server URL add https:// prefix all the time

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by fbricon** [comment]
-1 on that change:
- typing a bad url fills the log with stacktraces, everytime a character is entered : 
com.openshift.restclient.OpenShiftException: Malformed URL 'httpsfsf'
	at com.openshift.restclient.ClientFactory.create(ClientFactory.java:38)
	at org.jboss.tools.openshift.core.connection.ConnectionFactory.create(ConnectionFactory.java:53)
	at org.jboss.tools.openshift.core.connection.ConnectionFactory.create(ConnectionFactory.java:46)
	at org.jboss.tools.openshift.core.connection.ConnectionFactory.create(ConnectionFactory.java:1)
	at org.jboss.tools.openshift.common.ui.wizard.AbstractApplicationWorkbenchWizard$DelegatingConnectionWizardPage.hasWizard(AbstractApplicationWorkbenchWizard.java:120)
	at org.jboss.tools.openshift.common.ui.wizard.AbstractApplicationWorkbenchWizard$DelegatingConnectionWizardPage.canFlipToNextPage(AbstractApplicationWorkbenchWizard.java:61)
	at org.eclipse.jface.wizard.WizardDialog.updateButtons(WizardDialog.java:1322)
	at org.eclipse.jface.wizard.WizardPage.setPageComplete(WizardPage.java:293)
	at org.jboss.tools.common.ui.databinding.ParametrizableWizardPageSupport.handleStatusChanged(ParametrizableWizardPageSupport.java:70)
	at org.eclipse.jface.databinding.dialog.DialogPageSupport.statusProviderChanged(DialogPageSupport.java:223)
	at org.eclipse.jface.databinding.dialog.DialogPageSupport.access$2(DialogPageSupport.java:213)
	at org.eclipse.jface.databinding.dialog.DialogPageSupport$4.handleValueChange(DialogPageSupport.java:181)
	at org.eclipse.core.databinding.observable.value.ValueChangeEvent.dispatch(ValueChangeEvent.java:63)
	at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:119)
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.fireValueChange(AbstractObservableValue.java:74)
	at org.eclipse.core.databinding.observable.value.ComputedValue.makeDirty(ComputedValue.java:205)
	at org.eclipse.core.databinding.observable.value.ComputedValue$PrivateInterface.handleChange(ComputedValue.java:148)
	at org.eclipse.core.databinding.observable.ChangeEvent.dispatch(ChangeEvent.java:42)
	at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:119)
	at org.eclipse.core.databinding.observable.AbstractObservable.fireChange(AbstractObservable.java:71)
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.fireValueChange(AbstractObservableValue.java:73)
	at org.eclipse.core.databinding.observable.value.WritableValue.doSetValue(WritableValue.java:94)
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.setValue(AbstractObservableValue.java:58)
	at org.eclipse.core.databinding.ValueBinding$4.run(ValueBinding.java:252)
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:150)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:154)
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:172)
	at org.eclipse.core.databinding.ValueBinding.setValidationStatus(ValueBinding.java:249)
	at org.eclipse.core.databinding.ValueBinding.access$7(ValueBinding.java:248)
	at org.eclipse.core.databinding.ValueBinding$3$1.run(ValueBinding.java:215)
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:150)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:154)
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:172)
	at org.eclipse.core.databinding.ValueBinding$3.run(ValueBinding.java:196)
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:150)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:154)
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:172)
	at org.eclipse.core.databinding.ValueBinding.doUpdate(ValueBinding.java:158)
	at org.eclipse.core.databinding.ValueBinding.access$4(ValueBinding.java:147)
	at org.eclipse.core.databinding.ValueBinding$1.handleValueChange(ValueBinding.java:46)
	at org.eclipse.core.databinding.observable.value.ValueChangeEvent.dispatch(ValueChangeEvent.java:63)
	at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:119)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue.fireValueChange(DecoratingObservableValue.java:57)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue.handleValueChange(DecoratingObservableValue.java:99)
	at org.eclipse.core.databinding.observable.value.DecoratingObservableValue$1.handleValueChange(DecoratingObservableValue.java:72)
	at org.eclipse.core.databinding.observable.value.ValueChangeEvent.dispatch(ValueChangeEvent.java:63)
	at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:119)
	at org.eclipse.core.databinding.observable.value.AbstractObservableValue.fireValueChange(AbstractObservableValue.java:74)
	at org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue.notifyIfChanged(SimplePropertyObservableValue.java:127)
	at org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue.access$2(SimplePropertyObservableValue.java:119)
	at org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue$1$1.run(SimplePropertyObservableValue.java:69)
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:150)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:154)
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:172)
	at org.eclipse.core.internal.databinding.property.value.SimplePropertyObservableValue$1.handleEvent(SimplePropertyObservableValue.java:65)
	at org.eclipse.core.databinding.property.NativePropertyListener.fireChange(NativePropertyListener.java:65)
	at org.eclipse.jface.internal.databinding.swt.WidgetListener.handleEvent(WidgetListener.java:56)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at org.jboss.tools.central.internal.WizardSupport.openWizard(WizardSupport.java:73)
	at org.jboss.tools.central.editors.GettingStartedHtmlPage$8.run(GettingStartedHtmlPage.java:355)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard.openDialog(SetupWizard.java:457)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin$3.run(SetupUIPlugin.java:476)
	at org.eclipse.oomph.ui.UIUtil$3.run(UIUtil.java:424)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.net.MalformedURLException: no protocol: httpsfsf
	at java.net.URL.<init>(URL.java:586)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at com.openshift.restclient.ClientFactory.create(ClientFactory.java:36)

- The user has no visual feedback about the url being invalid

**Comment by alexeykazakov** [comment]
This PR doesn't improve validation. The same exception is thrown when typing bad url w/o this PR.
We have to switch to validation via new URL(url) to catch malformed URLs. Andre intentionally used regex for such validation instead of URL. I will make sure we don't break anything with new validation and will create a new PR.

**Comment by adietish** [comment]
I would not use URL since URL has a few very nasty gotchas where it'll try to reach out to the internets. If you dont believe in regex URI is mostly a better alternative to URL.

**Comment by alexeykazakov** [comment]
@adietish do you have a link or something where I can find details about this problems when new URL() is trying to connect to internet? I looked at its source and also googled but didn't find anything suspicious.

So, I have updated the PR. It looks like that we have to check both new URL() and URI() to cover all the cases of invalid urls w/o establishing a real connection. And it's fast enough for using in validation.

@fbricon, @adietish please take a look.

**Comment by fbricon** [comment]
new URL() is safe. Comparing URLs or putting them into Sets of Maps is bad. http://kwebble.com/blog/2014/08/09/javas-urlequals-uses-an-internet-connection

**Comment by fbricon** [comment]
Applied after a couple modifications, as https://github.com/jbosstools/jbosstools-openshift/commit/798c85698f90402bd7476517c26e0d194a16e5b7.

Thanks Alexey!

**Pull request closed without merging**
