### PR TITLE
[JBIDE-23841] added (resource) "Kind" to "Details" properties-tab

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@rhopp @jeffmaury please review

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury @bdshadow anyone please?

**Comment by rhopp** [comment]
I've tried this, works as expected. +1 from me.

**Comment by jeffmaury** [comment]
@adietish I can't see the new property for Build resources, is it desired ?

**Comment by adietish** [comment]
@jeffmaury good catch, Builds are the only property source which isnt showing it. It also wont show the cathegories ("Basic"), etc.
I dont know why yet.

**Comment by adietish** [comment]
@jeffmaury I'll file an issue for the BuildConfig missing the cathegories ("Basic", "Annotations", etc.) and therefore the "Kind", too. 
In the meantime, I'll merge this

**Comment by adietish** [comment]
@jeffmaury @rhopp +1 please?

**Comment by psrna** [comment]
Adding @jrichter1 as a QE backup, since Radim is on pto since Tomorrow.

**Comment by jrichter1** [comment]
Looks good to me. It seems no existing properties have changed, so the ITests should not be affected (I'll run the whole suite just to be sure). It's more likely we'll just need to add checks for the "Kind" since it is new.

**Comment by adietish** [comment]
@jrichter1 thanks for chiming in. Please update here once you had the ITs running so that I can merge it. Should I jira for the update in ITs where the "Kind" should be asserted, too?

**Comment by jrichter1** [comment]
@adietish you're good to go.
And regarding the jira, yeah, you could do that :)

**Comment by adietish** [comment]
@jrichter1 ok, cool. thanks.
Here you go: https://issues.jboss.org/browse/JBIDE-23885

**Pull request merged**
