### PR TITLE
jbide-24979: Scale up/down/to: NPE if you have only rc, no dc

### PR DESCRIPTION
**Pull request by bdshadow**
Signed-off-by: Dmitrii Bocharov <dbocharo@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
testPR

**Comment by bdshadow** [comment]
@adietish yes, i had the same. And did nothing with it as it is really not connected twith this jira

**Comment by adietish** [comment]
@bdshadow I agree on the fact that having the pod(s) show up twice needs a new jira, but I'd think that doing nothing (with no feedback) for some pod (that are shown) should be adressed in this jira? Wrong?

**Comment by bdshadow** [comment]
@adietish i agree that it's not ok to do nothing without feedback.
The reason, why nothing happens, is because we can't find rc for such pods, as we try to find services for them first and then replication controller. And this kind of pods don't have service as a parent, because their parent (in terms of `IResourceWrapper`s) is project.
The reason why we show it like this is in this PR: https://github.com/jbosstools/jbosstools-openshift/pull/1709/files#diff-fe25f5ebed5fcd00f5f86c6e04e1aba0R188. So my question is - is it a correct representation of the hierarchy of the resources? If yes - i'll try to retrieve the rc somehow in this jira. If no - it's a matter of another jira

**Comment by adietish** [comment]
@bdshadow thx for the explanations. The pods "belong" to the rc, which is displayed. What I dont understand is that this relation seems to be detected (pods are displayed as children to the rc), since I can scale the pods displayed as children to the rc. But I can't when they're displayed as children to the project. Looks like the visual representation defines if a pod can scale or not. 
On the other hand I get that doing resource queries (to overcome the missing relation to the rc in IResourceWrapper for the erroneously displayed pods) isn't possible since we're in UI thread here. 
I guess that we can leave this "bug" alone since we want to fix the double display bug and keep the pods that are displayed as children to the rc only, making this "bug" disappear. It could hit us later though. 
Agree?

**Comment by bdshadow** [comment]
@adietish agree :) 
PS
You are saying that 

> relation seems to be detected 

But it's not detected. We put it like this ourselves: https://github.com/jbosstools/jbosstools-openshift/pull/1709/files#diff-fe25f5ebed5fcd00f5f86c6e04e1aba0R192 and line 187 too.

**Comment by adietish** [comment]
@bdshadow so pods could end up listed below an rc that doesn't control them? sounds bad and worth a jira?

**Comment by bdshadow** [comment]
@adietish yes: https://issues.jboss.org/browse/JBIDE-26087

**Pull request merged**
