### PR TITLE
[JBIDE-25091] corrected resource limit unit labels

### PR DESCRIPTION
**Pull request by adietish**
Changes in this PR:

    * corrected duplicate MiB entry in units combo
    * added "..." to the end of the context menu entry since
    this is required if a context menu item is opening up a dialog
    * corrected button in Edit Resource limits wizard from "Finish"
    to "OK" since we have only 1 page
    * made sure the combos for memory and cpu limits are equal in
    width
    * moved rc/dc retrieval to job

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury please review and confirm +1 as discussed so that I can merge this

**Comment by bdshadow** [comment]
testPR

**Comment by adietish** [comment]
@bdshadow dare to review please?

**Comment by bdshadow** [comment]
@adietish i've reviewed it already. Made one comment in the jira: https://issues.jboss.org/browse/JBIDE-25091?focusedCommentId=13480437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13480437

**Pull request merged**
