### PR TITLE
[JBIDE-24775] dont classcast when creating new v3 connection

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@robstryker please review

**Comment by adietish** [comment]
the odd thing though is that extended properties are *NOT* saved though. See https://issues.jboss.org/browse/JBIDE-24768 which wants to *NOT* save them when cancelling the wizard. Hitting "Finish" though should save them, which it doesnt do - and i dont think that my patch is in any way responsible for this.

**Comment by adietish** [comment]
@robstryker please explain in what your solution at https://bluejeans.com/6504809063/ is superior. To me it just more complex without added benefits (1. instance var map storing extended vars that needs to be synced with the orig source 2. distinction btw. non connection objects, v2 and v3 connections)

**Comment by adietish** [comment]
in bluejeans we agree on
* using an instance var is need to temporarly store settings so that settings only get set to the connection once you hit "Finish", not saved if you hit "Cancel"
* map is a bad name for an instance var, it should be something like extendedProperties
* the extended properties map should be grouped with the other instance vars

**Comment by adietish** [comment]
@robstryker merged your changes and modified according to what we discussed in BJ. Please review.

**Comment by robstryker** [comment]
+1

**Comment by adietish** [comment]
maven build is passing locally (and remotely). cdk-/openshift-integration-tests are failing across PRs. @rhopp can you please look into these failures?

**Pull request merged**
