### PR TITLE
[JBIDE-23886] tell the user what type of resource we're deleting

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@psrna can you please review this change that's based on your suggestion in JBIDE-21895?

**Comment by psrna** [comment]
Thx for improving UI, Andre. I'll give it a try from your branch.

First what comes to my mind is that changing the Dialog titles will affect integration tests.

The labels need to be changed in openshift.reddeer too.

I see one reference e.g. here: https://github.com/jbosstools/jbosstools-openshift/blob/master/test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java

**Comment by adietish** [comment]
@psrna good catch! corrected the labels in the IT's accordingly.

**Comment by adietish** [comment]
all sonar complaints are false positives. It thinks that strings are passwords and occurring strings should be replaced by constants. This makes no sense in a class (OpenShiftLabel) in a bot-test framework that identifies titles.

**Comment by adietish** [comment]
@psrna please re-review

**Comment by psrna** [comment]
@adietish I've cloned your github branch and tried your enhancement.  Works well! +1

However I do not have time to re-run the whole itests suite. @jrichter1 will you give it a spin?

**Comment by jrichter1** [comment]
ITests are unharmed
chuck norris approved

**Comment by adietish** [comment]
@jrichter1 awesome, thanks for verifying :)
https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fadveischool.com%2Fwp-content%2Fuploads%2F2015%2F10%2Faudience-clapping.jpg&f=1

**Pull request merged**
