### PR TITLE
jbide-26160: Server Adapter stays in [Debugging] when you kill the pod

### PR DESCRIPTION
**Pull request by bdshadow**
Signed-off-by: Dmitrii Bocharov <dbocharo@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
the PR works for me, the server adapter is restarted into normal run-mode. But the app is actually still in debug mode, as one can see in the env variables that are present in the dc:
image
and in the new pod:
image
I am thus wondering if we shouldn't instead of restarting into normal run-model, restart the port forwarding to the new pod?

**Comment by bdshadow** [comment]
@adietish please, take a look

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@bdshadow looks like you have to rebase this for jenkins to get back to green (it fails with a baseline check that we fixed previously)

**Comment by adietish** [comment]
@bdshadow I just rebased and pushed it. Testing it now.

**Comment by bdshadow** [comment]
@adietish i can't replicate it. However, for me for some reason port forwarding isn't started in some cases. It doesn't happen all the time and i can't figure out why (everything is on listeners and timeouts, hard to debug and replicate the cases). I'll continue working on it...

**Comment by jeffmaury** [comment]
I did a test on Win10.
Here is what I did:
1) start the server adapter
2) restart in debug mode: pod is runnning in debug mode, oc port-forward running in the background, debug conf is connected to the local port
3) kill the pod: a new pod is restarted, it is in debug mode, but I can't see any oc running anymore and the debug conf says it's disconnected.

**Comment by jeffmaury** [comment]
I think I got a little explanation: it seems OpenShift sends an event when a new pod is created and claims its status is running but its containers are not yet them fully running. I notived that running `oc get pods -w`

```
eap-app-3-d9bs8   1/1       Terminating   0         3m        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app      
eap-app-3-87gtz   0/1       Pending   0         2s        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app          
eap-app-3-87gtz   0/1       Pending   0         2s        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app          
eap-app-3-87gtz   0/1       ContainerCreating   0         2s        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app
eap-app-3-87gtz   0/1       Running   0         6s        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app          
eap-app-3-d9bs8   0/1       Terminating   0         4m        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app      
eap-app-3-d9bs8   0/1       Terminating   0         4m        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app      
eap-app-3-d9bs8   0/1       Terminating   0         4m        application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app      
eap-app-3-87gtz   1/1       Running   0         52s       application=eap-app,deployment=eap-app-3,deploymentConfig=eap-app,deploymentconfig=eap-app          
```

Notice the 0/1 and then the 1/1 on the `eap-app-3-87gtz` pod.
So I think our listener may try to update a little bit too early sometimes.
But there is no way with the current rest client to detect that.
I also noted that when you switch the debug mode you will get an error because our listener will try to update the debug config too early. So as we have time before 4.11.0.AM1, I suggest to open an issue on the rest client to fill the gap and then continue on this one. Thoughts @adietish ?

**Comment by adietish** [comment]
@jeffmaury ok sounds like a very likely explanation. Didn't look into it, but I'd highly suggest that we should not simply delay by an arbitrary amount of time but when the system tells us that things are ready. Any idea on how to delay informing the listener?

**Comment by jeffmaury** [comment]
Yes we must update the client lib so that we can have the status of each of the containers of the pod

**Comment by adietish** [comment]
@jeffmaury grocked that as a concept but was wondering on more specific means. Do you know, are there?

**Comment by adietish** [comment]
@jeffmaury looking into openshift-restclient-java it seemes that the "only" problem is that it's only considering the status of the 1st container in a pod, when asking for the status of the pod?
https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/model/Pod.java#L89

**Comment by jeffmaury** [comment]
Yes, merging the statuses of all containers would fix the problem

**Comment by adietish** [comment]
I think that I might have found the problem:
The new pod gets into "Running" state but is not "ready" yet. We wait for the new pod to be running, but ignore this 2nd property. See here how the debugger is trying to connect and fails as soon as the new pod is "Running" but isn't ready yet:
```
       "containerStatuses" : [{
            "name" : "nodejs-mongo-persistent",
            "state" : {"running" : {"startedAt" : "2019-02-08T12:49:08Z"}},
            "lastState" : {},
            "ready" : false,
            "restartCount" : 0,
            "image" : "sha256:7bdfb6d33b917da75e94c5e6c67074bbc95be62ee2658632a2ed82b749a4e5c5",
            "imageID" : "docker-pullable://docker-registry.default.svc:5000/jbide25000-2/nodejs-mongo-persistent@sha256:4f2b1c1b85a61918ace38a90cd7e31f833891fb81cb84c104fbe43d5e1091103",
            "containerID" : "docker://f0963069f75d420bdf1206bdaeae5f792da70a837a1f8049d3bd75b9e351a857"
        }],
        "qosClass" : "Burstable"
    }
}

!ENTRY org.eclipse.wst.jsdt.chromium.debug.core 4 0 2019-02-08 13:49:12.196
!MESSAGE Failed to connect to Standalone V8 VM
!STACK 0
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at org.eclipse.wst.jsdt.chromium.internal.transport.AbstractSocketWrapper.<init>(AbstractSocketWrapper.java:35)
	at org.eclipse.wst.jsdt.chromium.internal.transport.SocketWrapper.<init>(SocketWrapper.java:29)
	at org.eclipse.wst.jsdt.chromium.internal.transport.SocketConnection.attach(SocketConnection.java:290)
	at org.eclipse.wst.jsdt.chromium.internal.transport.SocketConnection.start(SocketConnection.java:445)
	at org.eclipse.wst.jsdt.chromium.internal.standalonev8.StandaloneVmImpl.attachImpl(StandaloneVmImpl.java:121)
	at org.eclipse.wst.jsdt.chromium.internal.standalonev8.StandaloneVmImpl.attach(StandaloneVmImpl.java:79)
	at org.eclipse.wst.jsdt.chromium.debug.core.model.JavascriptVmEmbedderFactory$4$1.attach(JavascriptVmEmbedderFactory.java:207)
	at org.eclipse.wst.jsdt.chromium.debug.core.model.DebugTargetImpl.attach(DebugTargetImpl.java:74)
	at org.eclipse.wst.jsdt.chromium.debug.ui.launcher.LaunchTypeBase.launch(LaunchTypeBase.java:101)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by adietish** [comment]
@jeffmaury I have a patch for openshift-client-runtime that allows accessing the "ready" property within the container status: https://github.com/openshift/openshift-restclient-java/pull/362

**Comment by adietish** [comment]
I added commits where I use the updated openshift-restclient-java which is able to check a pods ready state and take this into account when waiting for the new pod. The new client library isn't available in maven repo yet, so jenkins ends up red of course.
Results dont seem to be consistent for me though. I now also get the following stack-trace:
```
org.eclipse.core.runtime.CoreException: Could not modify launch config for server wfl14 (Service) at OpenShift 3 (api.rh-us-east-1.openshift.com)
	at org.jboss.tools.openshift.core.server.OpenShiftServerUtils.toCoreException(OpenShiftServerUtils.java:713)
	at org.jboss.tools.openshift.core.server.OpenShiftServerUtils.toCoreException(OpenShiftServerUtils.java:717)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.attachRemoteDebugger(OpenShiftLaunchController.java:476)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.access$1(OpenShiftLaunchController.java:464)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController$3.onDebugChange(OpenShiftLaunchController.java:316)
	at org.jboss.tools.openshift.internal.core.server.debug.OpenShiftDebugMode.toggleDebugger(OpenShiftDebugMode.java:252)
	at org.jboss.tools.openshift.internal.core.server.debug.OpenShiftDebugMode.execute(OpenShiftDebugMode.java:186)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController.updateOpenShift(OpenShiftLaunchController.java:159)
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftLaunchController$4.connectionChanged(OpenShiftLaunchController.java:355)
	at org.jboss.tools.openshift.common.core.connection.ConnectionsRegistry.fireChange(ConnectionsRegistry.java:158)
	at org.jboss.tools.openshift.common.core.connection.ConnectionsRegistry.fireConnectionChanged(ConnectionsRegistry.java:115)
	at org.jboss.tools.openshift.internal.core.WatchManager$WatchListener.received(WatchManager.java:313)
	at com.openshift.internal.restclient.okhttp.WatchClient$WatchEndpoint.onMessage(WatchClient.java:189)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by adietish** [comment]
@jeffmaury rebase onto latest master

**Comment by adietish** [comment]
@jeffmaury is this ready to be tested?

**Comment by jeffmaury** [comment]
@adietish Yes

**Comment by adietish** [comment]
@jkopriva I have major problems to make this run properly. Could I ask you to please also try to verify this?

**Comment by adietish** [comment]
I finally managed to have this running successfully when using open.paas.redhat.com. Nevertheless it turned out to only work in tight premisses:
It only works for me with a clean new project and only when starting the adapter normally first and into debugging afterwards.

**Comment by adietish** [comment]
In a 1st try that didnt timeout on open.paas.redhat.com I have the new pod in debug mode, the port forwarding is stopped and the server adapter is in normal run mode (not debugging).

**Comment by adietish** [comment]
I think that I found the bug that made thing not work for me: the reference to the timer needs to be cleared so that subsequent tries re-create the timer). 
At the same time I extracted the listener code to it's own inner class to better separate things.
@jeffmaury dare to please test again?

**Comment by jeffmaury** [comment]
Works for me after latest @adietish fix.

**Comment by adietish** [comment]
@jeffmaury awesome, thx! merging since it now also works for me.

**Comment by bdshadow** [comment]
Great, that it's finally merged!

**Comment by jeffmaury** [comment]
Yeah we're slow now that you're on other topics 😄

**Pull request merged**
