### PR TITLE
[JBIDE-24745] switch to rest client 5.9.0.Final

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
can be merged once https://github.com/openshift/openshift-restclient-java/pull/281 is merged and restclient is deployed to the maven repository.

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Comment by jeffmaury** [comment]
@adietish @jcantrill there was a mistake about the identifier: 5.8.0.FINAL was released 5.8.0.Final is expected

**Comment by adietish** [comment]
@jeffmaury oh, my bad. Annoying. In the meantime a commit made it to the client master and turned the version to 5.9.0-SNAPSHOT. I therefore suggest that we release a 5.9.0.Final (correct spelling this time). Agree?

**Comment by adietish** [comment]
@jeffmaury is the erroneous spelling the cause of the jenkins failure or is it https://redhat.service-now.com/pnt?id=ticket&table=x_redha_pnt_devops_table&sys_id=e7d71c2613800bc0daa77b304244b0e2?

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@rhopp can you please verify the 5 test failures that are reported for https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/cdk3.prcheck/72/#showFailuresLink ? these failure are blocking this PR which we *MUST* merge before freeze

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
maven build is successfull local (and remotely). cdk-/openshift-integration-tests fail currently across the PRs with similar test failing, so that I dont think that those failures are caused by the current PRs

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@bdshadow please review

**Pull request merged**
