### PR TITLE
[JBIDE-23883] using openshift-restclient-5.5.0.Final

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury please review

**Comment by adietish** [comment]
@jeffmaury @nickboldt jenkins build failed, i notice it being quite unreliable. We should fix this otherwise devs will start to ignore jenkins results.

**Comment by adietish** [comment]
testPR

**Comment by bdshadow** [comment]
@adietish @nickboldt @jeffmaury 
I'm not sure, but i suspect that this may happen because of simultaneous builds: usual build and SonarQube one. For example, the last fail has message:
> ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress git@github.com:jbosstools/jbosstools-openshift.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

this may happen because at the same there was one more build running, which had already occupied the connection with the same credentials.
So i suggest to merge 2 these builds into one. It's not so difficult, i can do it as i've created SonarQube build

**Comment by adietish** [comment]
I didnt find a proper fix for a path to "oc" with spaces: https://issues.jboss.org/browse/JBIDE-23862?focusedCommentId=13364289&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13364289
Nevertheless we need to use the final version of the openshift-restclient-java in our JBoss Tools 4.4.3.Final. I'm thus merging this even though https://issues.jboss.org/browse/JBIDE-23862 is not fixed yet.

**Pull request merged**
