### PR TITLE
[JBIDE-21626] Fix deploy docker image

### PR DESCRIPTION
**Pull request by jcantrill**
The PR fixes deploying a docker image by:

* pulling metadata from a docker connection or via openshift imagestreamimport
* allows create of 'deploy image' resources without image metadata. deployment is dependent upon server being able to access image

cc @fbricon @adietish

### CODE REVIEW

**Comment by fbricon** [comment]
So, unless the docker image was pulled in my docker registry, the workflow doesn't seem to work as expected.

From OpenShift Explorer, having an empty project

- right-click Deploy Docker Image...
- search for guestbook, select the kubernetes/guestbook image
- an exception is logged:
```

com.openshift.restclient.authorization.ResourceForbiddenException: User "test-admin" cannot create imagestreamimports in project "gb"
	at com.openshift.internal.restclient.DefaultClient.createOpenShiftException(DefaultClient.java:477)
	at com.openshift.internal.restclient.DefaultClient.createVersion(DefaultClient.java:209)
	at com.openshift.internal.restclient.DefaultClient.create(DefaultClient.java:194)
	at com.openshift.internal.restclient.DefaultClient.create(DefaultClient.java:188)
	at com.openshift.internal.restclient.capability.resources.ImageStreamImportCapability.importImageInfo(ImageStreamImportCapability.java:41)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.importDockerMetaData(DeployImageWizardModel.java:512)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.getDockerMetaData(DeployImageWizardModel.java:270)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.initContainerInfo(DeployImageWizardModel.java:239)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.setImage(DeployImageWizardModel.java:222)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImagePage$2.widgetSelected(DeployImagePage.java:183)
```
- clicking next doesn't show the image info. We should be able to list the path and see port 3000 being exposed

**Comment by jcantrill** [comment]
@fbricon I was able to deploy:

I created a new vagrant OS instance using https://github.com/jcantrill/jctoolbox/openshift.  
I created a new project
from openshift side...deployed the referenced image and was able to pull and deploy the image
Confirmed my user is a regular user and not cluster:admin

I'm now going to try and deploy an image straight to a cluster with the image only being available on my local docker daemon to see if that is in fact possible.  I'm skeptical that it can be done without physically pushing the image to OS or dockerhub. cc @burrsutter

**Comment by jcantrill** [comment]
@fbricon Sacre blu!!! it does work...i will investigate!

**Comment by jcantrill** [comment]
@fbricon so playing around with new-app, image is only available on my local daemon https://gist.github.com/jcantrill/610877988fa137dda4fa  it created resources, but the pod never spins up.  Im certain if i were to push this image to my instance (or dockerhub) the magic would happen.  I'm pretty certain  this code is functioning as expected.  It would be nice for @burrsutter or @adietish or @mlabuda to take it through its paces

**Comment by xcoulon** [comment]
@jcantrill found the following issue when trying the patch: if you search/input `jboss/wildfly:8.1.0.Final` and click `Next`, the metadata show `WILDFLY_VERSION=10.0.0.Final`, so I suspect that it's the `latest` image metadata that were pulled.

**Comment by jcantrill** [comment]
@xcoulon I believe your issue is resolved by https://github.com/openshift/openshift-restclient-java/pull/122

**Comment by jcantrill** [comment]
@fbricon @xcoulon  pushed a minor update.  resolve the referenced issue.

**Comment by fbricon** [comment]
Still have the same problem, using the OpenShift version from the latest CDK build (March 3rd)

http://screencast.com/t/9eQsSbZ2trzm

**Comment by xcoulon** [comment]
Following the same steps as @fbricon with the latest CDK, I get this error when I select the `kubernetes/guestbook:latest` image with an empty project:

```
!ENTRY org.jboss.tools.openshift.ui 4 0 2016-03-04 16:31:39.691
!MESSAGE User "openshift-dev" cannot create imagestreamimports in project "foo"
!STACK 0
com.openshift.restclient.authorization.ResourceForbiddenException: User "openshift-dev" cannot create imagestreamimports in project "foo"
	at com.openshift.internal.restclient.DefaultClient.createOpenShiftException(DefaultClient.java:477)
	at com.openshift.internal.restclient.DefaultClient.createVersion(DefaultClient.java:209)
	at com.openshift.internal.restclient.DefaultClient.create(DefaultClient.java:194)
	at com.openshift.internal.restclient.DefaultClient.create(DefaultClient.java:188)
	at com.openshift.internal.restclient.capability.resources.ImageStreamImportCapability.importImageMetadata(ImageStreamImportCapability.java:41)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.importDockerMetaData(DeployImageWizardModel.java:512)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.getDockerMetaData(DeployImageWizardModel.java:270)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.initContainerInfo(DeployImageWizardModel.java:239)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImageWizardModel.setImage(DeployImageWizardModel.java:222)
	at org.jboss.tools.openshift.internal.ui.wizard.deployimage.DeployImagePage$2.widgetSelected(DeployImagePage.java:183)
```

however, it runs fine with the OS3 VM from http://openshift.org/vm (version 1.1.2)

**Comment by jcantrill** [comment]
We have resolved there is a difference in 'oc new-app' between the cdk image and origin.  Basically the older version tries to get metadata straight from dockerhub using the v2 registry api.  Currently working on fix to similiar functionality in the rest client to try and resolve this issue.

**Comment by fbricon** [comment]
this PR no longer cleanly rebase from jbosstools-4.3.x

**Comment by jcantrill** [comment]
@fbricon rebased on 4.3.x but I'm uncertain the conflicts resolved to the desired fucntionallity. Additionally with the addition of DockerHubRegistry I think we have a subtle conflict on an image existing.  The functionality introduced in the restclient queries for a v2 registry where the jbosstools code is looking for v1.  @xcoulon I think you should review the latest pull here and provide an opinion.

**Comment by jcantrill** [comment]
@fbricon @xcoulon  only obvious think I noticed is we are no longer allowing you to advance in the wizard if we are unable to find metadata. This PR used to allow you to continue but would require you to specify a port, which may or may not be a useful port.  If we do not want to allow someone to do this then this PR appears to resolve deploying an image.

**Comment by fbricon** [comment]
So it took me a while to find a random, non openshift docker image that'd deploy properly (exposing only 1 port), but I found saturnism/spring-boot-helloworld-ui:latest
It works well, except no deployment is being triggered. It needs to be triggered manually through the Deploy Latest menu, or from the web console.

**Comment by jcantrill** [comment]
merged

**Pull request closed without merging**
