### PR TITLE
JBIDE-25306 - Initial removal of openshift v2 plugins and features

### PR DESCRIPTION
**Pull request by robstryker**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

# DO NOT MERGE FOR AM2

### CODE REVIEW

**Comment by jeffmaury** [comment]
features/org.jboss.tools.openshift.express.feature/.project not deleted
features/org.jboss.tools.openshift.express.test.feature/.project

**Comment by adietish** [comment]
@jeffmaury your +1 for this?

**Comment by adietish** [comment]
@jeffmaury +1 please?

**Comment by adietish** [comment]
@robstryker dare to rebase please?

**Comment by nickboldt** [comment]
All I care about is that the plugins and feature are removed from the reactor (features/pom.xml: 2 features,  plugins/pom.xml: 3 plugins, tests/pom.xml: 1 test plugin) then removed from site/category.xml (2 features).

So... after a quick scan of those four files, +1. Seems legit.

**Comment by jkopriva** [comment]
@robstryker it looks good to me now, tests are ok with this change and I have not seen any openshift2 artifacts build during maven build.

**Pull request merged**
