### PR TITLE
[JBIDE-24498] improve info display in resource summary dialog

### PR DESCRIPTION
**Pull request by adietish**
* shortened imagestream error message
* display message type (warning, info, etc.)

Signed-off-by: Andre Dietisheim <adietish@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@odockal @jkopriva could anybody in QE please test this? It is important to also test how the resource summary looks in other cases like: 
* create application from a template
* create application from builder image
* template resource details
* create resource from json file

**Comment by adietish** [comment]
build fails because bot tests required egit.smartimport 4.8 which doesn't seem to be available:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.jboss.tools.openshift.ui.bot.test 3.7.0.qualifier
[ERROR]   Missing requirement: org.jboss.tools.openshift.ui.bot.test 3.7.0.qualifier requires 'osgi.bundle; org.eclipse.egit.ui.smartimport 4.8.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.jboss.tools.openshift.tests:org.jboss.tools.openshift.ui.bot.test:3.7.0-SNAPSHOT @ 
```

**Comment by jkopriva** [comment]
Created PR for ITests https://github.com/jbosstools/jbosstools-openshift/pull/1853

**Comment by adietish** [comment]
@jkopriva thx for the fix, merged it and rebased.

**Comment by jkopriva** [comment]
Hi @adietish, I have tried this json: https://github.com/jbosstools/jbosstools-openshift/blob/master/itests/org.jboss.tools.openshift.ui.bot.test/resources/hello-pod.json, in the old versions it works as expected, but your change throws an error:
!ENTRY org.jboss.tools.openshift.ui 4 -1 2019-07-10 08:15:37.141
!MESSAGE Unable to determine the api endpoint for kind 'Pod'
!STACK 0
com.openshift.restclient.UnsupportedEndpointException: Unable to determine the api endpoint for kind 'Pod'
	at com.openshift.internal.restclient.URLBuilder.buildWithNamespaceInPath(URLBuilder.java:149)
	at com.openshift.internal.restclient.URLBuilder.build(URLBuilder.java:135)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:294)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:275)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:243)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:226)
	at com.openshift.internal.restclient.DefaultClient.create(DefaultClient.java:201)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob$1.visit(CreateResourceJob.java:65)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob$1.visit(CreateResourceJob.java:1)
	at com.openshift.internal.restclient.model.KubernetesResource.accept(KubernetesResource.java:94)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob.loadResource(CreateResourceJob.java:52)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob.doRun(CreateResourceJob.java:47)
	at org.jboss.tools.openshift.internal.common.core.job.AbstractDelegatingMonitorJob.run(AbstractDelegatingMonitorJob.java:37)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Similar error happens for route:
!ENTRY org.jboss.tools.openshift.ui 4 -1 2019-07-10 08:14:56.939
!MESSAGE Unable to determine the api endpoint for kind 'Route'
!STACK 0
com.openshift.restclient.UnsupportedEndpointException: Unable to determine the api endpoint for kind 'Route'
	at com.openshift.internal.restclient.URLBuilder.buildWithNamespaceInPath(URLBuilder.java:149)
	at com.openshift.internal.restclient.URLBuilder.build(URLBuilder.java:135)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:294)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:275)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:243)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:226)
	at com.openshift.internal.restclient.DefaultClient.create(DefaultClient.java:201)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob$1.visit(CreateResourceJob.java:65)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob$1.visit(CreateResourceJob.java:1)
	at com.openshift.internal.restclient.model.KubernetesResource.accept(KubernetesResource.java:94)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob.loadResource(CreateResourceJob.java:52)
	at org.jboss.tools.openshift.internal.ui.job.CreateResourceJob.doRun(CreateResourceJob.java:47)
	at org.jboss.tools.openshift.internal.common.core.job.AbstractDelegatingMonitorJob.run(AbstractDelegatingMonitorJob.java:37)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


I have also tried running ITests and there were a lot of failures: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/job/openshift.itests.noCDK/534/

**Comment by jeffmaury** [comment]
@jkopriva this is not related to this PR but rather to the changes we've made in the client library for OCP4 compatibility. Can you open an issue in https://issues.jboss.org/projects/OSJC/issues and assign to me ?

**Comment by jkopriva** [comment]
@jeffmaury Hi, thanks, I have created JIRA: https://issues.jboss.org/browse/OSJC-287 , but I cannot assign it to you(I suppose I do not have permissions :( ).

**Comment by adietish** [comment]
@jkopriva yes, that's not related to the change in UI I did. Other than the issue that you thankfully found, is this PR working for you?

**Comment by jkopriva** [comment]
@adietish otherwise it looks good, I have tested it on Win10. I just have a one note when using application templates: there is a button for copying parameters, but it copies all parameters, I cannot select e.g. just repo URL to copy it. This could be worth adding.

**Comment by adietish** [comment]
@adietish ok, fair point. But then, I would consider this as a separate issue that we could tackle in a separate enhancement request. If infos are displayed in a better way and nothing else got broken, I'd consider this as done.

**Comment by adietish** [comment]
@jkopriva can you please +1 this PR if you agree?

**Comment by jkopriva** [comment]
@adietish issue is created: https://issues.jboss.org/browse/JBIDE-26738

**Pull request merged**
