### PR TITLE
Partially provides a fix for JBIDE-27871

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by robstryker** [comment]
I am unable to merge this without a review. Going on PTO.

**Review by jeffmaury — COMMENTED** [review]
LGTM, waiting for @adietish test on MacOS

**Comment by adietish** [comment]
@robstryker, @jeffmaury I installed via Preferences > Server > Runtime Environment > Add > JBoss 6.x Runtime > Download and install runtime... > JBoss 6.0.0 and could not reproduce this issue without your patch. Missing something?

**Comment by jeffmaury** [comment]
See https://issues.redhat.com/browse/JBIDE-27871?focusedCommentId=16377742&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16377742

**Review by adietish — APPROVED** [review]
fixes the issue that I described in https://issues.redhat.com/browse/JBIDE-27871: no CRC 1.28 is listed any more.

**Pull request merged**
