### PR TITLE
JBIDE-24804 - ResourceLabelsPageModel should never set instance var t…

### PR DESCRIPTION
**Pull request by robstryker**
…o unmodifiable list

Signed-off-by: Rob Stryker <rob@oxbeef.net>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by robstryker** [comment]
I actually feel strongly that this is the right solution. We don't want random people who call setLabels to be able to add an unmodifiable list, which would prevent addLabel working in the future. We also might not want someone who is a listener to the model to be able to change the model directly without using the model's methods itself. 

So I strongly believe that it is appropriate for the events to be fired with unmodifiable lists, and for setLabels(etc) to properly protect the model by instantiating a new instance of a modifiable list. 

It's also worth noting that this was Dmitri's solution on the JIRA, and I agree with his solution.

**Comment by jeffmaury** [comment]
I agree with you that setLabels is the right place to set a modifiable lib. But then why are we duplicating the list as an unmodifiable one before calling setLabels. I would keep your code but modify addLabel, removeLabel and updateLabel not to pass an unmodifiable list

**Comment by adietish** [comment]
@jeffmaury where do you see the code duplicating into an unmodifiable list and then calling #setLabels? Couldn't find such occurrences, just the property firing which is using those unmodifiable list which doesnt seem utterly wrong to me?

**Comment by jeffmaury** [comment]
Have a look at the `addLabel` method as an example

**Comment by bdshadow** [comment]
i agree with @jeffmaury and i don't think it makes sense to `fireIndexedPropertyChange` with wrapping lists into `Collections.unmodifiableList` all the time

**Comment by robstryker** [comment]
It makes perfect sense to send out unmodifiable lists. This way the listener who gets the list can't make edits to the list except through the approved API of 'addLabel'.   

If you send out a normal list, that can be modified, any listener can simply add items to the list. This will bypass the model's own internal recordkeeping. If a listener decides to add or remove items from the list directly, any OTHER listeners won't get events!

**Comment by jcantrill** [comment]
It is my understanding that consumer's of a fired event are receiving:

* What property changed
* The new value(s)
* The old value(s)

It's my opinion is that 'old' values should be unmodifiable; its a 'fact' used to make some determination and not really designed to be alterable.   The code should probably copy the set into a new one so that it can be modified by subsequent calls.

**Comment by jeffmaury** [comment]
I'm not against unmodifiable lists. I'm just curious why we need so may copies when processing a single operation (add/remove label)

**Comment by adietish** [comment]
@jeffmaury #addLabel creates 2 new collections:
1) the old list, so that it can fire it
2) an unmodifiable copy of the new list (so that listeners can't modify it).

I dont see what's wrong with that agreeing with the arguments brought up by @robstryker and @jcantrill. 

+1 for this PR.

**Pull request merged**
