### PR TITLE
[JBIDE-23862] prefs: dont allow oc on path with " "

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury @bdshadow couldnt fix the issue with " " in the path to the oc binary. I am thus for now suggesting that we error in the preferences if such a path is being used.

**Comment by bdshadow** [comment]
changed this PR a bit, i think it should be also merged today before the code freeze

**Comment by jeffmaury** [comment]
I think we need @adietish comment before merging because I remember he had remarks about it

**Comment by adietish** [comment]
@bdshadow @jeffmaury by looking at the PR things look fine. I was investigating this and didnt find a proper solution to fix spaces in paths for OSX (I tried minimalistic code). Let me test it properly.

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury @bdshadow it looks like there are only issues on MacOS when the path to oc contains spaces (in jira @jeffmaury said that it works with spaces in Win10, @robstryker told me that it also works with spaces on Linux - @bdshadow can you confirm this please? @jeffmaury can you please specify in jira what you were referring to when talking of problems when the path to the workspace contains spaces?)
If it's true, that only MacOS has this problem, then the validaiton should only fail for spaces on MacOS (it currently does for all platforms).
Thoughts?

**Comment by bdshadow** [comment]
@adietish i have problems of Fedora. I put the oc into "/home/dbocharo/oc folder with space".
The version is detected fine in the Preferences windows. However, when i tried to create a server adapter (where oc is actually used), i got the following error:
```java
org.eclipse.core.runtime.CoreException: Error while publishing server jboss-eap70-openshift (Service) at OpenShift 3 (10.1.2.2).  Could not sync all pods to folder /home/dbocharo/dev/openshift/runtime-eclipse_with_openshift/.metadata/.plugins/org.jboss.ide.eclipse.as.core/sample-project@jboss-eap70-openshift/deploy
	at org.jboss.tools.openshift.core.server.behavior.OpenShiftPublishController.publishStart(OpenShiftPublishController.java:73)
	at org.jboss.ide.eclipse.as.wtp.core.server.behavior.CachedPublisherProfileBehavior.publishStart(CachedPublisherProfileBehavior.java:47)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:942)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3172)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Contains: Does your OpenShift binary location exist? Error starting process: Cannot run program ""/home/dbocharo/oc": error=2, No such file or directory
```

**Comment by bdshadow** [comment]
I guess the problem happens [here in openshift-restclient](https://github.com/openshift/openshift-restclient-java/blob/c725ccf1069b5e92aa58905e419992d0a945bb9e/src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java#L156) where we create the command to execute and split it with spaces. The final `oc rsync` with parameters turns into a mess

**Comment by bdshadow** [comment]
and i'm sure it doesn't work on any OS. At least, it must fail here.

**Comment by bdshadow** [comment]
So your check should be added. It's a good quick fix to avoid these problems, even if we plan changes in restclient in the future

**Comment by adietish** [comment]
went back to simply bumping the openshift-restclient-java since this fixes the issue. No change in JBoss Tools.
Thanks for being tenacious @bdshadow!

**Pull request merged**
