### PR TITLE
[JBIDE-20569] reorganized OpenShift Explorer context menu

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jkopriva can we please have this run in jenkins? I started running the test-suite locally but it takes a hell lot of a time. I'd be happy if we could delegate this to jenkins.

**Comment by adietish** [comment]
testPR

**Comment by jkopriva** [comment]
@adietish Hi, I have retested it locally against https://console.engint.openshift.com and it looks good. I have also started ITests on Jenkins, but I think there will be failures due to changes in menu.

**Comment by adietish** [comment]
@jkopriva I made sure that I changed the labels in the ITests, so I'd hope that tests work fine (could have missed something though). Why do you think that jenkins would fail? Have a link to the build that you launched please?

**Comment by adietish** [comment]
pushed further changes in the ITests, relaunched ITests in jenkins.

**Comment by jkopriva** [comment]
@adietish jenkins build is ok: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift.itests/308/ - 1 failure, but it is unrelated to this PR

**Pull request merged**
