### PR TITLE
[JBIDE-22114] have a public setter #setDeployProject in model for the…

### PR DESCRIPTION
**Pull request by adietish**
… binding

### CODE REVIEW

**Comment by adietish** [comment]
@fbricon plz review

**Comment by fbricon** [comment]
+1 to apply.
@alexeykazakov please confirm

**Comment by alexeykazakov** [comment]
+1 to merge to 4.3.x

**Comment by adietish** [comment]
merged into jbosstools-4.3.x and cherry-picked into master

**Pull request closed without merging**
