### PR TITLE
jbide-24539: Explorer, Properties: User should be able to see what

### PR DESCRIPTION
**Pull request by bdshadow**
please, merge only after https://github.com/openshift/openshift-restclient-java/pull/278 is merged

### CODE REVIEW

**Comment by adietish** [comment]
+1, works for me

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@bdshadow you should switch to use openshift-restclient-java 5.8.0-SNAPSHOT since that's the current version in the rest client

**Comment by bdshadow** [comment]
testPR

**Comment by bdshadow** [comment]
tests passed. PR was approved @adietish . Merging

**Pull request merged**
