### PR TITLE
JBIDE-27788 : fix wizard NPE when SSO fails.

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by sbouchet** [comment]
partial Fix to remove the NPE when SSO fails on the first page of the wizard. it's not fixing the SSO failure itself.

**Review by jeffmaury — COMMENTED** [review]
LGTM

**Review by jeffmaury — APPROVED** [review]

**Comment by odockal** [comment]
@sbouchet approved, can we merge?

**Comment by sbouchet** [comment]
> @sbouchet approved, can we merge?

no, we're still on code freeze and we need the proper approval to merge this and respin release.

**Comment by odockal** [comment]
@sbouchet Ah, ok, I tried and it seems to work.

**Pull request merged**
