### PR TITLE
Jbide 23490

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury seems to work for me. Can you please also test this?

**Comment by adietish** [comment]
since this is a new feature, ideally QE should also +1 this, @jrichter1 can you please?

**Comment by jrichter1** [comment]
What I (perhaps wrongly) understand from the jira is, that I should be able to create and use server adapters linked to pods, even if a service is not available. Please correct me if I got this wrong.

Anyway, the findings so far:
 - I can create server adapters from pods - and they tell me what resource they are linked with (service or deployment config)
 - adapters created when a service exists work fine
 - adapters without a service look like their functionality does something, but I can't get to the actual deployed application to see what I've published - things like show in... just don't do anything

**Comment by adietish** [comment]
@jrichter1 I believe that that's how it is supposed to work. Since there's no service, there's no route nor way to get to view the content from the outside. @jeffmaury ?

**Comment by jeffmaury** [comment]
This feature is focused on the publish and debug. This is also targeted to non UI deployement (FUSE). There is no direct way from the UI to invoke the deployment but this is still possible through the port forward. We could have this done automatically in the future if a service is not available BTW having a service is not enough we must have a route so this is not new

**Comment by adietish** [comment]
@jeffmaury @jrichter1 looks like things are thus working as expected. merging.

**Comment by jeffmaury** [comment]
# **PLEASE DO NOT MERGE**
 until I gave an ok. Given the importance of the change, we should wait for the next sprint, we are to close to the GA

**Comment by jeffmaury** [comment]
Closed by #1427

**Pull request closed without merging**
