### PR TITLE
[JBIDE-22299] add icons to templates and image builders

### PR DESCRIPTION
**Pull request by fbricon**
Adding icons to the templates list : 

Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Comment by adietish** [comment]
nice addition!

**Comment by adietish** [comment]
There's a test class for the label provider. Dare to add tests?

**Comment by fbricon** [comment]
yeah but we (as in @jcantrill)  explicitly ignored getImage tests in OpenShiftExplorerLabelProviderTest (`Skipping getImage tests as they can't be run headless`) to be able to run it as pure junit test

**Comment by adietish** [comment]
@fbricon: pure unit test? what's the harm to at least check if an image is returned?

**Comment by adietish** [comment]
+1. LGTM

**Comment by jcantrill** [comment]
@fbricon way to call me out!

**Comment by fbricon** [comment]
@jcantrill you're welcome :-)

@adietish I'll add the tests

**Comment by jcantrill** [comment]
@fbricon  what would be even cooler...is if you pulled the icon we display when you select the image (e.g. ruby, rails) ... but i dont think any of them are scaled correctly... +1 LGTM

**Comment by fbricon** [comment]
Added getImage tests

@jcantrill pulling the image icons can maybe be done (if they were scaled properly), but that'd be part of a separate JIRA.

**Pull request merged**
