### PR TITLE
[JBIDE-22704] - Application Wizard: Application based on builder images do not have prefilled configuration

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
@mlabuda do we have this covered with a bot-test?

**Comment by mlabuda** [comment]
Nope. There are tests only when wizard is opened from context menu of a project. Test for opening from shell menu and central are missing, but current tests for handling builder image wizard are easily extensible for those use cases too.

**Comment by adietish** [comment]
+1, tested the PR, works for me.

**Comment by adietish** [comment]
@mlabuda ok, we should then try to do such a bot test. @jeffmaury agree?

**Comment by mlabuda** [comment]
Yeah, we should. The tests are located at https://github.com/jbosstools/jbosstools-integration-tests/blob/master/tests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/BuilderImageApplicationWizardHandlingTest.java

**Comment by fbricon** [comment]
Merged as a bot test will need to live in a separate repo anyway

**Pull request merged**
