### PR TITLE
JBIDE-24438 - Read port from Connection URL

### PR DESCRIPTION
**Pull request by apupier**
read port from Server Adapter Connection URL instead of using an
hardcoded one. It is also taking care when no port is specified (such as
open.paas.redhat.com and surely most of publicly available instances)

I don't know how to unit test it as there are several static methods and tests are not in the same package (no fragment used). Suggestions?

### CODE REVIEW

**Comment by adietish** [comment]
@robstryker dare to review this please?

**Comment by robstryker** [comment]
So... I like the patch for ensuring that the connection is correct when using createConnection(). 

However, if the details are likely to change (ie a pod is shut down and a new one brought up), wont this jmx connection then go stale? Don't you need a listener somewhere to respond and either change the details of the connection or remove it and create a new one?

**Comment by apupier** [comment]
> However, if the details are likely to change (ie a pod is shut down and a new one brought up), wont this jmx connection then go stale? Don't you need a listener somewhere to respond and either change the details of the connection or remove it and create a new one?

yes, the JMX connection won't be working anymore, see https://issues.jboss.org/browse/JBIDE-25288
but it is not due to this port. The port of the global connection will remain the same.

**Comment by jeffmaury** [comment]
testPR

**Pull request merged**
