### PR TITLE
JBIDE-24387 Implement cleanup for reddeer requirements

### PR DESCRIPTION
**Pull request by jrichter1**
#1490 for 4.4.x so @rhopp doesn't need to cherry pick stuff eventually :)

### CODE REVIEW

**Comment by rhopp** [comment]
testPR

**Comment by jrichter1** [comment]
testPR

**Comment by jrichter1** [comment]
testPR

**Comment by rhopp** [comment]
testPR

**Comment by rhopp** [comment]
testPR

**Comment by rhopp** [comment]
testPR

**Pull request merged**
