### PR TITLE
 [JBIDE-25700] added warning when using oc < 3.11 on linux

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@odockal @jkopriva dare to review this please since you had found the various issues that are now linked to JBIDE-25700?

**Comment by adietish** [comment]
@jkopriva @odockal sec, please hold. I'll include more changes...

**Comment by adietish** [comment]
@jkopriva @odockal please review, I'll create an additional, separate PR for the other changes that also need to be done

**Comment by odockal** [comment]
@adietish I will take a look and try it out tomorrow, hopefully will be "sickless"...

**Comment by adietish** [comment]
@odockal great, thx. Maybe better review https://github.com/jbosstools/jbosstools-openshift/pull/1774 instead of this one since it includes this one and has another issue fixed.
Get well!

**Comment by adietish** [comment]
replacing this by PR #1774

**Pull request closed without merging**
