### PR TITLE
JBIDE-22225: Node.js Debugging support for OpenShift applications

### PR DESCRIPTION
**Pull request by ibuziuk**
This PR should be merged only once target platform will consume Neon.1 bits. Please, review assuming that the changes for JSDT Neon.1 can be done no later than September, 8th. After this date Neon.1 RC4 will be released and it will not be possible to do any changes in upstream

### CODE REVIEW

**Comment by ibuziuk** [comment]
testPR

**Comment by adietish** [comment]
wohoo, \o/
Any shortcomings left that we should look into?

**Comment by ibuziuk** [comment]
@adietish I have updated the PR  - now when the debug session ends all changes are republished via

`server.publish(IServer.PUBLISH_INCREMENTAL, new NullProgressMonitor());`

No more shortcomings were spotted

**Comment by alexeykazakov** [comment]
See https://issues.jboss.org/browse/JBIDE-22225?focusedCommentId=13286285&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13286285

**Pull request closed without merging**
