### PR TITLE
JBIDE-25617 - ensure skip registration responds to changes

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by robstryker** [comment]
Basically, moved the skip-registration flag area to performOverrides instead of initialize()

**Comment by adietish** [comment]
@robstryker dare to address the following sonar complaint?
```public void initialize(ILaunchConfigurationWorkingCopy wc, String userName, IServer server) throws CoreException {```
while CoreException doesnt seem to be thrown anywhere in the method body.

**Comment by robstryker** [comment]
The interface throws the exception. I don't change the signature for implementers even if this specific implementation doesn't throw it. All callers need to be aware it could be thrown.

**Comment by adietish** [comment]
@robstryker ok looked it up, ack'ed

**Pull request merged**
