### PR TITLE
JBIDE-26179 add "Refresh..." button in New OpenShift Application wizard

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
@adietish can you please review?

**Comment by adietish** [comment]
great stuff, works very fine for me in the application wizard. 
But the server adapter wizard was crushed UI wise though:
image

**Comment by jkopriva** [comment]
@adietish Thanks, it should be fixed now, can you please review that once again?

**Comment by adietish** [comment]
@jkopriva +1, works now. Thx!

**Comment by adietish** [comment]
testPR

**Pull request merged**
