### PR TITLE
jbide-25590: connection is not refreshed if you modify its url

### PR DESCRIPTION
**Pull request by bdshadow**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
works for me, +1
Could we please also have a test (that could at least verify that firing happens)?

**Comment by bdshadow** [comment]
@adietish sure, working on it
@jeffmaury  maybe we handle this case, but how should it expand (i mean, to the project layer? or to the services? if to the services layer then should we do this for all projects?)

**Comment by jeffmaury** [comment]
I would expand to the project level if the previous one was expanded

**Comment by bdshadow** [comment]
@jeffmaury ok, i'll take a look if it is not difficult to implement. If so, i'll include it into this pr

**Comment by bdshadow** [comment]
@jeffmaury i can't find how to understand that the connection(or project, or service) is expanded. Do you have an idea how to check it?

**Comment by adietish** [comment]
@bdshadow I suggest that we merge this for now and provide the enhancement in a further jira.

**Comment by adietish** [comment]
@bdshadow you can tell the TreeViewer to expand via TreeViewer#expandToLevel

**Comment by bdshadow** [comment]
@adietish :( i was making a test. Still wanted to merge it
Also the question is not HOW to expand the tree. Look at [Jeff's comment above](https://github.com/jbosstools/jbosstools-openshift/pull/1704#issuecomment-374878221): "... if the previous one was expanded". How to understand that the previous one was expanded? In general - how to detect that TreeViewer is expanded to some level?

**Pull request merged**
