### PR TITLE
Refactoring cdk.reddeer plugin to use RedDeer 2.0

### PR DESCRIPTION
**Pull request by odockal**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by odockal** [comment]
Branch for testing RedDeer 2.0 refactoring, do not merge yet.

**Comment by odockal** [comment]
I think that this PR is ready to be reviewed and merged, eventually.

**Comment by jkopriva** [comment]
looks good to me +1
@bdshadow can you please also review?

**Comment by odockal** [comment]
We might also want to wait for https://github.com/jbosstools/jbosstools-openshift/pull/1539 to be merged, rebase and do review afterwards.

**Comment by jkopriva** [comment]
@odockal we don't have to wait for #1539, I will prepare new commit in #1539 based on this PR

**Comment by odockal** [comment]
I see, alright, @jkopriva good idea.

**Pull request merged**
