### PR TITLE
[JBIDE-25506] exclude .git, .npm when rsync'ing

### PR DESCRIPTION
**Pull request by adietish**
Signed-off-by: Andre Dietisheim <adietish@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
this depends on https://github.com/openshift/openshift-restclient-java/pull/319

**Comment by adietish** [comment]
@jeffmaury please review

**Comment by adietish** [comment]
@jkopriva @jeffmaury this is the successor/better fix for the "dont transfer .git, .npm, etc." (JBIDE-25506): it prevents .git but also .npm from syncing. Please review (requires building https://github.com/openshift/openshift-restclient-java/pull/319 first)

**Comment by adietish** [comment]
testPR

**Comment by jkopriva** [comment]
@adietish I have retested this on Win10 and F27 and .npm files are not transferred.

**Comment by adietish** [comment]
@jkopriva thx!

**Pull request merged**
