### PR TITLE
[JBIDE-23014] - Allow connections to configure the cluster namespace from which to get clusterwide templates

### PR DESCRIPTION
**Pull request by jeffmaury**
- Update for templates

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
@adietish please review

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury how can I test this? I am guessing that I should add templates to a namespace that's different from openshift. Do you know how to do this?

**Comment by jeffmaury** [comment]
@adietish one simple way to test is to change the common namespace to a non existing namespace and try to deploy an app. You should see no templates and builders

**Comment by adietish** [comment]
@nickboldt @mickaelistria somehow the testPR trigger isnt working any more. See current state of the jenkins check (executed 1d 20h ago, while I commented "testPR" 2h ago and no new build/check was triggered since then)
CC @jeffmaury

**Comment by jeffmaury** [comment]
I did want to implement such a check because it will be costly. Unless data bind supports the notion of delayed check (not on every keystroke)

**Pull request merged**
