### PR TITLE
[JBIDE-22278] Show OpenShift Explorer when a new Connection is created

### PR DESCRIPTION
**Pull request by fbricon**
OpenShift Explorer is shown when creating the OpenShift Connection from the CDK server adapter or the regular New OpenShift Application wizard.

http://screencast.com/t/j6EWxqS2adP

Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Comment by scabanovich** [comment]
I wonder if OpenShift 2 core plugin may start after OpenShift UI plugin. Then the listener will be notified that some connections are added (if there is an OpenShift 2 connection in the workspace) - and the explorer will be opened right on start. Listener may check that the connection is an instance of OpenShift 3.

**Comment by fbricon** [comment]
mmm I haven't checked if a connection added event is fired on workspace startup. If it does, then it's probably not a good idea to always show the openshift explorer on startup.

Putting that issue aside, the listener should probably be added to the common ui plugin instead. The explorer should be shown regardless of the connection type.

I'll do some more testing

**Comment by fbricon** [comment]
Moved the listener to the common plugin. Makes sense to have both new OS 2 & 3 connections trigger the OpenShift explorer visibility.

The explorer won't get displayed until the OS2 or 3 plugins are activated.

Also added some IT.

**Comment by scabanovich** [comment]
Looks good to me.

**Pull request merged**
