### PR TITLE
corrected EGitUtils#checkoutBranch to compile with EGit 5.2.0

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
Jenkins wont work currently because it's using TP 4.10.
On the other hand when building locally using the following command:
```
mvn clean verify -Dtpc.version=4.11.0.AM1-SNAPSHOT
```
tycho fails with the following error:
```
[ERROR] Failed to execute goal on project org.jboss.tools.openshift.core: Could not resolve dependencies for project org.jboss.tools.openshift.plugins:org.jboss.tools.openshift.core:eclipse-plugin:3.6.0-SNAPSHOT: The following artifacts could not be resolved: org.jboss.tools.openshift.plugins:org.jboss.tools.openshift.client.source:jar:lib/openshift-restclient-java-7.0.0.Final.jar:3.6.0.qualifier, org.jboss.tools.openshift.plugins:org.jboss.tools.openshift.client:jar:lib/openshift-restclient-java-7.0.0.Final.jar:3.6.0.qualifier: Could not find artifact org.jboss.tools.openshift.plugins:org.jboss.tools.openshift.client.source:jar:lib/openshift-restclient-java-7.0.0.Final.jar:3.6.0.qualifier at specified path /Users/adietish/Documents/jboss-workspaces/jbosstools-github/jbosstools-openshift/plugins/org.jboss.tools.openshift.client/lib/openshift-restclient-java-7.0.0.Final.jar -> [Help 1]
```
@jeffmaury @nickboldt do you know why this happens, I'm clueless?

**Comment by jeffmaury** [comment]
testPR (after parent update)

**Comment by jeffmaury** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury want to merge it now that the build passed?

**Comment by jeffmaury** [comment]
@adietish can't merge the title says DO NO MERGE :)

**Comment by adietish** [comment]
@jeffmaury thx :)

**Pull request merged**
