### PR TITLE
use user values for devmode-key, debugport-key & -value

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@apupier dare to review please?

**Comment by apupier** [comment]
I created https://issues.jboss.org/browse/JBIDE-25096
Might worth to edit commit message to include the JIRA number

I still reproduce the issue with this branch.
i tried with a Camel s2i-java images but it should nothing specific for it.

image

I'm using an Editor although the class modified is named XXXWizardpageXXX , was it another issue?

**Comment by bdshadow** [comment]
testPR

**Comment by adietish** [comment]
@apupier editing should now work, the 2nd commit did implement this. Dare to test/review?

**Comment by apupier** [comment]
editing with the editor is now working.
So I don't know to which use case was related the first commit.
Is it when effectively trying to debug a launched instance on OpenShift of an application? How to test that? Which OpenShift images are supporting that? eap?

**Comment by adietish** [comment]
@apupier if you look at the code and the commit, you'll see that the 1st commit fixes the model while the 2nd does the editor.

**Comment by adietish** [comment]
@apupier on how to test it: 
1) set values for debugging and debugging port key and port value
2) save the editor & restart the server adapter in debug (otherwise debugging port settings will not get used)
3) in OpenShift explorer: selected your service and pick "Manage Environment Variables..."
-> Verify that the settings are used as env variables
image

**Comment by adietish** [comment]
@apupier I filed this to https://issues.jboss.org/browse/JBIDE-25126. Yes there are rules, i noticed this when testing this PR. I implemented those when trying to solve https://issues.jboss.org/browse/JBIDE-25108. The rules are as follows: ```start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name', or 'MY_NAME', or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*'```

**Pull request merged**
