### PR TITLE
JBIDE-23675 - Move openshift reddeer wrapper classes from integration-tests repo to jbosstoos-openshift repo.

### PR DESCRIPTION
**Pull request by psrna**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by psrna** [comment]
depends on https://github.com/jbosstools/jbosstools-central/pull/392

**Comment by adietish** [comment]
testPR

**Comment by psrna** [comment]
testPR

**Comment by adietish** [comment]
FYI: dependency to central was removed, tests rewritten to test via File > New > Other > OpenShift which is equivalent to opening via central. Thus the dependency to central could be dropped.

**Comment by psrna** [comment]
@adietish, dependency to central was removed from openshift.reddeer test-framework. The only dependency was CentralIsLoaded condition, which is now here: 

https://github.com/jbosstools/jbosstools-openshift/blob/master/test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/CentralIsLoaded.java

The tests have not been rewritten as it turned out that the wizard launched from central behaves not the same as from File -> New -> Other -> Openshift. Here is regression bug: https://issues.jboss.org/browse/JBIDE-23704

So there obviously is a need for having tests for this scenario. And central is usually the first thing that is seen by a user.

**Pull request merged**
