### PR TITLE
 [JBIDE-26694] added deployment page to server editor

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jkopriva can you please test this with the steps in JIRA?

**Comment by adietish** [comment]
I think that the "Deployment" page should by default filter and only show the workspace projects that are added as module to the server adapter that one is editing. Showing all available ones, feels confusing.

**Comment by adietish** [comment]
@jkopriva can you please review this? It basically works even though there are 2 gotchas, which I'd like to address in a separate issues: 
* once the war name is changed, deployment to this new name is only done once you clean (ctx menu entry)
* the old deployment is not removed

**Comment by jkopriva** [comment]
Hi @adietish, can you please review jenkins build? There is compilation error. Thank you!

**Comment by adietish** [comment]
@jkopriva thx for pointing out. Turns out a bump in the required as.ui plugin version wasn't included in the commit

**Comment by adietish** [comment]
@jkopriva thx!

**Pull request merged**
