### PR TITLE
[JBIDE-24010] bump core and client plugins

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@nickboldt even though the plugins that changed and the feature that includes them are bumped,
the baseline check complains about the following I dont get:
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.26.0:compare-version-with-baselines (default) on project org.jboss.tools.openshift.egit.integration.feature: Duplicate version but different content found for (org.jboss.tools.openshift.egit.integration.feature.source.feature.jar/3.3.2.v20161213-1011). Also exists in baseline, but its content is different. -> [Help 1]
```

**Comment by jeffmaury** [comment]
You must delete the Maven repo for the baseline check to work correctly. This is what I did for master branch

**Comment by jeffmaury** [comment]
I validated your PR following:
- delete the local Maven repo (I think disabling Tycho local Maven repo resolution should be enough but forgot to remember how to do it)
- use Tycho 1.0.0 (as Tycho 0.26 has a bug in the baseline check for source feature)

**Comment by nickboldt** [comment]
Ah, forgot about the Tycho 0.26 bug. 

We could move 4.4.x branch to Tycho 1.0 if you'd like...? If so, see https://issues.jboss.org/browse/JBIDE-23212

**Comment by adietish** [comment]
@jeffmaury @nickboldt thanks for looking into this and providing insights!

**Pull request merged**
