### PR TITLE
JBIDE-25262 - ensure server state can be stopped if minishift-home disappears

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by robstryker** [comment]
@adietish i just re-tested it and it works 100% for me.  Steps:
1) Start CDK server
2) rm -rf ~/.minishift
3) right-click server, select stop. 

At this point the error log comes up: 

java.lang.Exception: The minishift-home for server "Container Development Environment 3.2+ rob" does not exist: /home/rob/.minishift

Please make sure that the virtual machine associated with this server has been properly shutdown.
	at org.jboss.tools.openshift.cdk.server.core.internal.adapter.controllers.CDK3ShutdownController.stop(CDK3ShutdownController.java:38)

The server is set to stopped.

**Comment by jeffmaury** [comment]
Tested on Windows (with some limitations as some file hold by the VM cannot be deleted).. Got an error reported: 
image

**Comment by adietish** [comment]
@jeffmaury what is the state of your adapter after the error? It should be [stopped]

**Comment by adietish** [comment]
@robstryker these were exactly the steps I took, and the stopping job kept running for me.

**Comment by jeffmaury** [comment]
It was changed to the `Stopped` state

**Comment by adietish** [comment]
@robstryker @jeffmaury tested again, now it stops, but I have no error like the one that you reported.

**Comment by jeffmaury** [comment]
@adietish what's your error then ?

**Comment by robstryker** [comment]
@adietish  seems to be experiencing the correct behavior. The server is set to stopped and the error log has the proper error. 

I think this patch is good for merge.

**Comment by adietish** [comment]
@robtryker I'd expect an error like @jeffmaury is reporting?

**Pull request merged**
