### PR TITLE
[JBIDE-23764] Scale To: display current (not desired) replicas

### PR DESCRIPTION
**Pull request by adietish**
# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by adietish** [comment]
@jeffmaury @bdshadow please review this 1-liner

**Comment by adietish** [comment]
@bdshadow @jeffmaury anyone please?

**Comment by bdshadow** [comment]
testPR

**Comment by bdshadow** [comment]
@adietish take a look at tests, please. Some of them are failing.

**Comment by adietish** [comment]
indeed, missed those. I'll fix the issues and add missing test-cases

**Comment by adietish** [comment]
testPR

**Comment by adietish** [comment]
@jeffmaury @bdshadow +1 please?

**Comment by adietish** [comment]
@jeffmaury thanks!

**Pull request merged**
