### PR TITLE
jbide-23165:NPE in in New OpenShift Application Wizard

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by adietish** [comment]
if I make sure I have <New Connection>, "OpenShift 3" selected, but no host nor credentials, I get the following error with your patch:
```
com.openshift.restclient.OpenShiftException: Unable to initialize client
	at com.openshift.restclient.ClientBuilder.build(ClientBuilder.java:201)
	at org.jboss.tools.openshift.core.connection.ConnectionFactory.create(ConnectionFactory.java:55)
	at org.jboss.tools.openshift.core.connection.ConnectionFactory.create(ConnectionFactory.java:1)
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPageModel.createConnection(ConnectionWizardPageModel.java:402)
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPageModel.connect(ConnectionWizardPageModel.java:340)
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPage$ConnectJob.doRun(ConnectionWizardPage.java:448)
	at org.jboss.tools.openshift.internal.common.core.job.AbstractDelegatingMonitorJob.run(AbstractDelegatingMonitorJob.java:37)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:620)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at com.openshift.restclient.ClientBuilder.build(ClientBuilder.java:192)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:525)
	... 10 more

!ENTRY org.eclipse.core.jobs 4 2 2016-09-26 16:26:22.098
!MESSAGE An internal error occurred during: "Verifying user credentials...".
!STACK 0
java.lang.NullPointerException
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPageModel.setConnectedStatus(ConnectionWizardPageModel.java:425)
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPageModel.update(ConnectionWizardPageModel.java:186)
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPageModel.connect(ConnectionWizardPageModel.java:362)
	at org.jboss.tools.openshift.internal.common.ui.connection.ConnectionWizardPage$ConnectJob.doRun(ConnectionWizardPage.java:448)
	at org.jboss.tools.openshift.internal.common.core.job.AbstractDelegatingMonitorJob.run(AbstractDelegatingMonitorJob.java:37)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
This makes me think that there's an erroneous attempt to initialize the client, still

**Comment by bdshadow** [comment]
@jeffmaury i agree, and that's what i [fixed here](https://github.com/jbosstools/jbosstools-openshift/pull/1328/files#diff-a5ea2b24015c398b7fc89e35cd623348R109). 
And seems to me that this problem has been always existing, we just didn't bump into it.

Jeff, i checked the case when URL is a single space, but could press Back button without any problems

**Comment by adietish** [comment]
Here's what I suggest as a better fix (based on this PR) vs what looks partially like a workaround to me: https://github.com/jbosstools/jbosstools-openshift/pull/1334

**Comment by adietish** [comment]
Here's what I suggest as a better fix (based on this PR) vs what looks partially like a workaround to me: #1334

**Comment by adietish** [comment]
@bdshadow dare to review and comment #1334 please?

**Comment by bdshadow** [comment]
@adietish i like your idea with reversing checks more. I'm testing your PR

**Comment by adietish** [comment]
closing this PR as it'll get replaced by #1334 once all issue in that one are solved.

**Pull request closed without merging**
