### PR TITLE
[JBIDE-22612] Force OpenShift 3 core plugin startup along the UI plugin

### PR DESCRIPTION
**Pull request by fbricon**
This feels like a fugly hack. But it works. 
However I'd be willing to accept any other solution that would be more elegant than this.
cc @adietish @jcantrill @jeffmaury @scabanovich

### CODE REVIEW

**Comment by scabanovich** [comment]
I think the fix is good provided that connections are loaded in start(BundleContext) methods of plugins.

Another  solution may be to load ConnectionsRegistry fully in ConnectionsRegistrySingleton.getInstance() inside synchronized block like

	private static boolean loaded = false;
	public static ConnectionsRegistry getInstance() {
		if(loaded) return model;
		synchronized (lock) {
			if(model != null) return model;
			model = new ConnectionsRegistry();
			//Do loading here or in ConnectionsRegistry constructor
			//Get loader participants from an extension point, and call them.
			loaded = true;
		}	
		return model;
	}
Loaders should be registered with an extension point.
Then acquiring ConnectionsRegistry should never be done from start() method of plugin activators.
In this way, bundles will start without a hindrance and any client of ConnectionsRegistry will receive it fully loaded. Listeners that are now added in start() methods also can be added with the extension point, after the registry is loaded.

**Comment by jeffmaury** [comment]
Why are we not using the startup extension point ?

**Comment by jeffmaury** [comment]
Why are we forcing the user to see the Openshift explorer ? What if he decides to remove this view ?

**Comment by adietish** [comment]
@jeffmaury that's exactly why the view should be the trigger for loading the connections. If there's no view no loading happens and no view is shown.
I really feel like we should find a way so that the explorer (view) is triggering the core plugin activation.
@fbricon can you please add steps to https://issues.jboss.org/browse/JBIDE-22612 so that I can reproduce?

**Comment by adietish** [comment]
I cant reproduce the problem with v3 but with v2: my v2 plugins are not activated, I thus cant add v2 connections (connection wizard wont offer the v2 connection type)

**Comment by fbricon** [comment]
@adietish can you check if the patch fixes your v2 issue?

@jeffmaury @scabanovich I also believe connections should be loaded from an extension point, but I wanted to get a simple fix working first

**Comment by fbricon** [comment]
@jeffmaury not having the view opened when the working on openshift doesn't make sense.
The view will only open when the openshift plugins are started, i.e. either because the view is already visible, or the user accesses some openshift feature

**Comment by adietish** [comment]
superseeded by #1230

**Pull request closed without merging**
