### PR TITLE
New integration tests for CDK/minishift server adapter profiles feature

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
@odockal do you have green build?

**Comment by odockal** [comment]
@jkopriva https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/job/cdk.minishift.itests/168/ those are for minishift server adapter. For cdk, results are coming.

**Comment by odockal** [comment]
@jkopriva And cdk itests: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/job/cdk.itests/480/, so far, rhel and win10 are green. Win7 is still going, but as a slave it is minor.

**Comment by odockal** [comment]
testPR

**Pull request merged**
