### PR TITLE
[JBIDE-20174] Fix missing project when deploy image from context project menu

### PR DESCRIPTION
**Pull request by jcantrill**
Fixes:
* The project drop down not being populated when right click context menu on a project

### CODE REVIEW

**Comment by jcantrill** [comment]
@fbricon @adietish  review?

**Comment by fbricon** [comment]
+1 to apply to 4.3.x. Make sure you rebase your branch before merging

**Comment by jcantrill** [comment]
closing as merged into 4.3.x

**Comment by fbricon** [comment]
I cherry picked the commit into master

**Pull request closed without merging**
