### PR TITLE
JBIDE-25210 ImportApplicationWizardTest stabilization fixes

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
Green build on Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/openshift.itests/43/

**Comment by adietish** [comment]
@jkopriva doing

**Comment by adietish** [comment]
running ImportApplicationWizardTest individually (not within the suite) fails for me with the following error:
```
org.eclipse.reddeer.core.exception.CoreLayerException: No matching widget found with Matcher matching when all matchers match: [Matcher matching widget with the same type as or type extending class org.eclipse.swt.widgets.Composite, wicth class name 'TabbedPropertyList']
class org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1[shell: 'junit-workspace - Eclipse Platform']
	class org.eclipse.swt.widgets.Composite[shell: 'junit-workspace - Eclipse Platform']
		class org.eclipse.ui.part.PageBook[shell: 'junit-workspace - Eclipse Platform']
			class org.eclipse.swt.widgets.Tree[shell: 'junit-workspace - Eclipse Platform']

	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:112)
	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:85)
	at org.eclipse.reddeer.swt.widgets.AbstractWidget.<init>(AbstractWidget.java:75)
	at org.eclipse.reddeer.eclipse.ui.views.properties.TabbedPropertyList.<init>(TabbedPropertyList.java:51)
	at org.eclipse.reddeer.eclipse.ui.views.properties.TabbedPropertyList.<init>(TabbedPropertyList.java:39)
	at org.jboss.tools.openshift.reddeer.view.resources.OpenShiftProject.selectTabbedProperty(OpenShiftProject.java:183)
	at org.jboss.tools.openshift.reddeer.view.resources.OpenShiftProject.getOpenShiftResources(OpenShiftProject.java:99)
	at org.jboss.tools.openshift.reddeer.view.resources.OpenShiftProject.getOpenShiftResources(OpenShiftProject.java:83)
	at org.jboss.tools.openshift.reddeer.condition.OpenShiftResourceExists.getResources(OpenShiftResourceExists.java:149)
	at org.jboss.tools.openshift.reddeer.condition.OpenShiftResourceExists.test(OpenShiftResourceExists.java:126)
	at org.eclipse.reddeer.common.wait.WaitUntil.stopWaiting(WaitUntil.java:102)
	at org.eclipse.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:146)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:131)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:96)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:63)
	at org.eclipse.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:49)
	at org.jboss.tools.openshift.reddeer.requirement.OpenShiftServiceRequirement.waitForUI(OpenShiftServiceRequirement.java:225)
	at org.jboss.tools.openshift.reddeer.requirement.OpenShiftServiceRequirement.fulfill(OpenShiftServiceRequirement.java:146)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.runSafely(Requirements.java:109)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.lambda$0(Requirements.java:104)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.runSafely(Requirements.java:104)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.fulfill(Requirements.java:75)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:56)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:152)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 1 s.: widget is found
	at org.eclipse.reddeer.common.wait.WaitUntil.throwWaitTimeOutException(WaitUntil.java:121)
	at org.eclipse.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:205)
	at org.eclipse.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:150)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:131)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:96)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:63)
	at org.eclipse.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:49)
	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:107)
	... 54 more
```

Adding 
```
@OpenPerspective(value=JBossPerspective.class)
public class ImportApplicationWizardTest extends ImportApplicationBase {	
```
fixes it

**Comment by adietish** [comment]
Next problem is a failure in ```ImportApplicationWizardTest#testImportOpenShift3AppViaServerAdapterSettings```
```
java.lang.Exception: Unexpected exception, expected<org.jboss.tools.openshift.ui.bot.test.common.OpenshiftTestInFailureException> but was<org.eclipse.reddeer.common.exception.WaitTimeoutExpiredException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunBefores.evaluate(RunBefores.java:84)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeTestExtensions.evaluate(RunIBeforeTestExtensions.java:72)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfters.evaluate(RunAfters.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterTestExtensions.evaluate(RunIAfterTestExtensions.java:58)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.runChild(RequirementsRunner.java:170)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunBeforeClasses.evaluate(RunBeforeClasses.java:80)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:56)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:152)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: control is enabled
	at org.eclipse.reddeer.common.wait.WaitUntil.throwWaitTimeOutException(WaitUntil.java:121)
	at org.eclipse.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:205)
	at org.eclipse.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:150)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:131)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:96)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:63)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:49)
	at org.eclipse.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:37)
	at org.eclipse.reddeer.swt.impl.button.AbstractButton.click(AbstractButton.java:56)
	at org.eclipse.reddeer.jface.wizard.WizardDialog.next(WizardDialog.java:120)
	at org.jboss.tools.openshift.ui.bot.test.application.v3.adapter.ImportApplicationWizardTest.testImportOpenShift3AppViaServerAdapterSettings(ImportApplicationWizardTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunTestMethod.evaluate(RunTestMethod.java:47)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 45 more

java.lang.AssertionError: The following shells remained open [Import OpenShift Application, OpenShift Server Adapter Settings]
	at org.junit.Assert.fail(Assert.java:88)
	at org.eclipse.reddeer.junit.extension.after.test.impl.CloseAllShellsExt.run(CloseAllShellsExt.java:81)
	at org.eclipse.reddeer.junit.extension.after.test.impl.CloseAllShellsExt.runAfterTest(CloseAllShellsExt.java:74)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterTestExtensions.evaluate(RunIAfterTestExtensions.java:71)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.runChild(RequirementsRunner.java:170)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunBeforeClasses.evaluate(RunBeforeClasses.java:80)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:71)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:67)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:56)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:152)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by adietish** [comment]
we agreed to postpone the requirement to run tests individually. I'm therefore running the whole suite for now, filed the requirement to https://issues.jboss.org/browse/JBIDE-25282

**Comment by adietish** [comment]
when run as suite, tests pass for me.

**Pull request merged**
