### PR TITLE
JBIDE-22463 - Update CDK code after API change in Docker tooling

### PR DESCRIPTION
**Pull request by xcoulon**
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Is this change backward compatible or does it require the newer version of Docker Tools?

**Comment by fbricon** [comment]
Yup, probably need to add a version constraint on Docker Tools

**Comment by mickaelistria** [comment]
If possible, yes, a version constraint would be fine.
Please ping again when this PR is ready, so we can merge the PR about TP and this one at the same time, avoiding a build failure.

**Comment by fbricon** [comment]
So yeah the current code doesn't compile in Eclipse Neon RC2. So the version constraint is required along the TP change

**Comment by xcoulon** [comment]
@fbricon  @mickaelistria I added a constraint on the Docker tooling to use 2.0.0. Please let me know if this is good enough, or if a specific timestamp is required.

**Comment by nickboldt** [comment]
=2.0.0 should be fine unless there's a future API break between 2.0.0.x and 2.0.0.y, in which case SPECIFIC version of 2.0.0 is needed.

You could also protect against future problems (if you expect them) using [2.0.0,2.0.1) or [2.0.0,2.1.0) as appropriate.

When do you plan to merge this?

**Comment by mickaelistria** [comment]
I merged the change in TP, please merge this one ASAP.

**Pull request merged**
